fix: [CDS-99032]: update project
harness/terraform-provider-harness pull request #1012
Opened 2024-07-16 13:23 UTC by shivamnegi94

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

2024-07-18 17:26 UTC, mteodor commented on internal/service/platform/gitops/project/resource_gitops_project_test.go
> +	agentId := "account.rollouts"
why is this hardcoded

2024-07-18 17:35 UTC, mteodor commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +										Computed:    true,
does this means we cant create appproject with our own annotations?

2024-07-18 17:42 UTC, mteodor commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +													Optional:    true,
is this what you wanted to have both optional and computed true?

2024-07-18 17:49 UTC, mteodor commented
in the documentation there is a section for import , ther is a typo at the end of line `.../<query_name` , missing `>`
```
# Import an Org level Gitops Repository
terraform import harness_platform_gitops_repository.example <organization_id>/<agent_id>/<query_name
```
have you tested if this works, also what is query name?

2024-07-19 04:16 UTC, shivamnegi94 commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +										Computed:    true,
No, it is optional

2024-07-19 04:17 UTC, shivamnegi94 commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +													Optional:    true,
Few fields are present in response by default which we need to set in terraform state

2024-07-19 04:18 UTC, shivamnegi94 commented on internal/service/platform/gitops/project/resource_gitops_project_test.go
> +	agentId := "account.rollouts"
I will fix it

2024-07-19 07:45 UTC, abosii-harness requested changes
There is a lot of fields that are part of the Kuberentes logic that customer shouldn't have to configure, any reasons why we want to expose these as part of our terraform?

2024-07-19 07:45 UTC, abosii-harness commented on docs/data-sources/platform_gitops_project.md
> +subcategory: ""
This should be manually changed back to Next Gen

2024-07-19 07:45 UTC, abosii-harness commented on docs/resources/platform_gitops_project.md
> +subcategory: ""
This should be manually changed back to Next Gen

2024-07-19 07:45 UTC, abosii-harness commented on internal/service/platform/gitops/project/data_source_gitops_project.go
> +				Optional:    true,
Are we sure that this should be optional? What will happen if we try to create a project without the project configuration?

2024-07-19 07:45 UTC, abosii-harness commented on internal/service/platform/gitops/project/data_source_gitops_project.go
>  							Optional:    true,
metadata as well sounds like something that should be required and either name or generate_name also

2024-07-19 07:45 UTC, abosii-harness commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +									"self_link": {
Why customer would want to configure self_link?

2024-07-19 07:45 UTC, abosii-harness commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +									"self_link": {
The same would apply to the uuid, resource_version, generation. These fields are generated by Kubernetes

2024-07-19 07:45 UTC, abosii-harness commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +									"owner_references": {
This field is also handled by Kubernetes controller

2024-07-19 07:45 UTC, abosii-harness commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +												"uid": {
This field is also handled by Kubermets

2024-07-22 05:22 UTC, RajBaviskar approved these changes

2024-07-22 05:22 UTC, RajBaviskar commented on docs/data-sources/platform_gitops_project.md
> +subcategory: ""
+1

2024-07-22 07:19 UTC, mteodor commented on docs/resources/platform_gitops_project.md
> +terraform import harness_platform_gitops_app_project.example <agent_id>/<query_name>
agent_id used in import expression is actually agent id prefixed with account prefix
similar for org
not sure how to document this well
so it would be 
```
terraform import harness_platform_gitops_app_project.example account.accounscopedagentid/app-project-name
```

```
terraform import harness_platform_gitops_app_project.example default/org.orgscopedagentid/app-project-name
```

```
terraform import harness_platform_gitops_app_project.example default/project_id/projectscopedagentid/app-project-name
```
not sure how to properly document this, this is missing in other places also

2024-07-22 07:19 UTC, mteodor commented on docs/resources/platform_gitops_project.md
> +terraform import harness_platform_gitops_app_project.example <organization_id>/<agent_id>/<query_name>
`query_name` this is actuall project name, right? if so lets make it `<organization_id>/<agent_id>/<app_proj_name>` so that it is selfexplanatory

2024-07-22 07:22 UTC, shivamnegi94 commented on docs/resources/platform_gitops_project.md
> +terraform import harness_platform_gitops_app_project.example <organization_id>/<agent_id>/<query_name>
ok

2024-07-22 07:32 UTC, shivamnegi94 commented on docs/resources/platform_gitops_project.md
> +terraform import harness_platform_gitops_app_project.example <agent_id>/<query_name>
I have added the prefix for the import which should be understandable to users.

2024-07-22 08:56 UTC, mteodor commented on examples/resources/harness_platform_gitops_project/resource.tf
> +      namespace  = "rollouts"
if we can add comment above that this namespace must match the namespace where agent is installed
agent-namespace

2024-07-22 09:42 UTC, abosii-harness commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +									"owner_references": {
we should get rid of owner_references

2024-07-22 09:43 UTC, abosii-harness commented on internal/service/platform/gitops/project/resource_gitops_project.go
> +						"status": {
I don't think this is something that you can set manually and is handled by controller. @mteodor to confirm

2024-07-22 11:52 UTC, mteodor approved these changes

2024-07-22 12:35 UTC, abosii-harness approved these changes

2024-07-23 03:29 UTC, merged