adding terraform support to env group
harness/terraform-provider-harness pull request #195
Opened 2022-09-09 20:55 UTC by RajBaviskar

2022-09-13 15:42 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/data_source_environment_group.go
> +			"type": {
i dont see type field in in our spec

2022-09-13 15:44 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		OrgIdentifier :=     (d.Get("org_id").(string))
variable name should start with small alphabet

2022-09-13 15:45 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		Branch:     optional.NewString(d.Get("branch").(string)),
use helpers.BuildField instead of optional.NewString(d.Get("branch").(string)),

2022-09-13 15:48 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		return diag.FromErr(errors.New("either identifier or name must be specified"))
we cant get environment group from right?

2022-09-13 15:52 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/data_source_environment_group_test.go
> +			name = harness_platform_environment_group.test.name
in environment group we dont have an api to get by name right?

2022-09-13 15:54 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/resource_environment_group.go
> +	helpers.SetMultiLevelResourceSchema(resource.Schema)
environment group is only project level resource right? it is not available at org and account level

2022-09-13 15:55 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/resource_environment_group.go
> +	OrgIdentifier :=     (d.Get("org_id").(string))
variable name should be small

2022-09-13 15:56 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/resource_environment_group.go
> +		Branch:     optional.NewString(d.Get("branch").(string)),
use helpers.BuildField instead of optional.NewString(d.Get("branch").(string))

2022-09-13 16:13 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/resource_environment_group_test.go
> +			type = "PreProduction"
environment group doest have type

2022-09-13 23:19 UTC, RajBaviskar commented on internal/service/platform/environment_group/data_source_environment_group.go
> +			"type": {
removed.

2022-09-13 23:19 UTC, RajBaviskar commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		OrgIdentifier :=     (d.Get("org_id").(string))
changed.

2022-09-13 23:19 UTC, RajBaviskar commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		Branch:     optional.NewString(d.Get("branch").(string)),
changed.

2022-09-13 23:20 UTC, RajBaviskar commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		return diag.FromErr(errors.New("either identifier or name must be specified"))
yup, removed.

2022-09-13 23:20 UTC, RajBaviskar commented on internal/service/platform/environment_group/data_source_environment_group_test.go
> +			name = harness_platform_environment_group.test.name
removed.

2022-09-13 23:20 UTC, RajBaviskar commented on internal/service/platform/environment_group/resource_environment_group_test.go
> +			type = "PreProduction"
removed.

2022-09-19 05:47 UTC, rathodmeetsatish commented on helpers/schema.go
> +func SetMultiLevelResourceSchemaForEnvGroup(s map[string]*schema.Schema) {
its not used i guess we can remove this or if we are using it we can move it env group resource

2022-09-19 05:48 UTC, rijajoo requested changes

2022-09-19 05:48 UTC, rijajoo commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		resp, _, err = c.EnvironmentGroupApi.GetEnvironmentGroup(ctx, d.Get("identifier").(string), c.AccountId, orgIdentifier, projectIdentifier, &nextgen.EnvironmentGroupApiGetEnvironmentGroupOpts{
resp, httpResp, err
Otherwise we are just sending a nil value.

2022-09-19 05:48 UTC, rijajoo commented on internal/service/platform/environment_group/resource_environment_group.go
> +	resp, _, err := c.EnvironmentGroupApi.GetEnvironmentGroup(ctx, d.Id(), c.AccountId, orgIdentifier, projectIdentifier, &nextgen.EnvironmentGroupApiGetEnvironmentGroupOpts{
Same here.

2022-09-19 05:48 UTC, rijajoo commented on internal/service/platform/environment_group/resource_environment_group.go
> +		resp, _, err = c.EnvironmentGroupApi.PostEnvironmentGroup(ctx, c.AccountId, &nextgen.EnvironmentGroupApiPostEnvironmentGroupOpts{
Same here.

2022-09-19 05:48 UTC, rijajoo commented on internal/service/platform/environment_group/resource_environment_group.go
> +		resp, _, err = c.EnvironmentGroupApi.UpdateEnvironmentGroup(ctx, d.Id(), c.AccountId, &nextgen.EnvironmentGroupApiUpdateEnvironmentGroupOpts{
Same here.

2022-09-19 05:48 UTC, rijajoo commented on internal/service/platform/environment_group/resource_environment_group.go
> +	_, _, err := c.EnvironmentGroupApi.DeleteEnvironmentGroup(ctx, d.Id(), c.AccountId, orgIdentifier, projectIdentifier, &nextgen.EnvironmentGroupApiDeleteEnvironmentGroupOpts{
Same here.

2022-09-19 05:48 UTC, rijajoo commented on internal/service/platform/environment_group/resource_environment_group.go
> +		return diag.Errorf(err.(nextgen.GenericSwaggerError).Error())
Call helpers.HandleApiError method here.

2022-09-19 05:49 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/data_source_environment_group.go
> +	helpers.SetProjectLevelDataSourceSchema(resource.Schema)
mention the schema similar to the way done in env group resource file

2022-09-19 05:50 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/resource_environment_group.go
> +				Optional:    true,
can you check if this should be required true?

2022-09-19 19:54 UTC, RajBaviskar commented
I had to create the EPIC for better tracking. When renamed this branch it asked me to create a new PR. https://github.com/harness/terraform-provider-harness/pull/203. Git is preserving all the old commits as well. Please review the new PR. Once I merge that PR, I'll close this marking as duplicate.  NEW PR - https://github.com/harness/terraform-provider-harness/pull/203

2022-09-19 19:54 UTC, RajBaviskar commented on internal/service/platform/environment_group/resource_environment_group.go
> +				Optional:    true,
made required.

2022-09-19 19:56 UTC, RajBaviskar commented on internal/service/platform/environment_group/data_source_environment_group.go
> +	helpers.SetProjectLevelDataSourceSchema(resource.Schema)
added.

2022-09-19 19:56 UTC, RajBaviskar commented on internal/service/platform/environment_group/resource_environment_group.go
> +		return diag.Errorf(err.(nextgen.GenericSwaggerError).Error())
changed.

2022-09-19 19:56 UTC, RajBaviskar commented on internal/service/platform/environment_group/data_source_environment_group.go
> +		resp, _, err = c.EnvironmentGroupApi.GetEnvironmentGroup(ctx, d.Get("identifier").(string), c.AccountId, orgIdentifier, projectIdentifier, &nextgen.EnvironmentGroupApiGetEnvironmentGroupOpts{
added

2022-09-19 19:56 UTC, RajBaviskar commented on helpers/schema.go
> +func SetMultiLevelResourceSchemaForEnvGroup(s map[string]*schema.Schema) {
removed.

2022-09-26 16:02 UTC, closed without merging