Upgrade user group documentation
harness/terraform-provider-harness pull request #241
Opened 2022-10-13 04:14 UTC by rathodmeetsatish

2022-10-13 19:00 UTC, RajBaviskar approved these changes

2022-10-17 10:20 UTC, rashminandasahoo requested changes

2022-10-17 10:20 UTC, rashminandasahoo commented on docs/resources/platform_usergroup.md
> +      When the SSO Provider is of LDAP type, the following values need to be populated:
The following fields need to be populated for LDAP SSO Providers:

2022-10-17 10:20 UTC, rashminandasahoo commented on docs/resources/platform_usergroup.md
> +      1) linked_sso_id
Is there a sequence for this? If not, we can remove the numbering and make it a bulleted list.

2022-10-17 10:20 UTC, rashminandasahoo commented on docs/resources/platform_usergroup.md
> +      When the SSO Provider is of SAML type, the following values need to be populated:
The following fields need to be populated for SAML SSO Providers:

2022-10-17 10:20 UTC, rashminandasahoo commented on docs/resources/platform_usergroup.md
> +Resource for creating a Harness User Group.Linking SSO providers with User Groups:
Space is missing after "User Group."

2022-10-17 10:20 UTC, rashminandasahoo commented on docs/resources/platform_usergroup.md
> +		When the SSO Provider is of LDAP type, the following values need to be populated:
Refer to the previous comments.

2022-10-17 10:20 UTC, rashminandasahoo commented on docs/resources/platform_usergroup.md
> +		1) linked_sso_id
Refer to the previous comments.

2022-10-17 10:20 UTC, rashminandasahoo commented on docs/resources/platform_usergroup.md
> +		When the SSO Provider is of SAML type, the following values need to be populated:
Refer to the previous comments.

2022-10-17 10:20 UTC, rashminandasahoo commented on internal/service/platform/usergroup/usergroup.go
> +		When the SSO Provider is of SAML type, the following values need to be populated:
Refer to the previous comments.

2022-10-19 18:33 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +  Resource for creating a Harness User Group.Linking SSO providers with User Groups:
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +      When the SSO Provider is of LDAP type, the following values need to be populated:
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +      1) linked_sso_id
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +      When the SSO Provider is of SAML type, the following values need to be populated:
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +Resource for creating a Harness User Group.Linking SSO providers with User Groups:
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +		When the SSO Provider is of LDAP type, the following values need to be populated:
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +		1) linked_sso_id
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on docs/resources/platform_usergroup.md
> +		When the SSO Provider is of SAML type, the following values need to be populated:
done

2022-10-19 18:34 UTC, rathodmeetsatish commented on internal/service/platform/usergroup/usergroup.go
> +		When the SSO Provider is of SAML type, the following values need to be populated:
done

2022-10-20 08:00 UTC, rashminandasahoo approved these changes

2022-10-20 08:01 UTC, merged