Add vault connector resource
harness/terraform-provider-harness pull request #250
Opened 2022-10-19 04:47 UTC by rathodmeetsatish

2022-10-19 09:25 UTC, rijajoo commented on internal/service/platform/connector/vault.go
> +		DeleteContext: resourceConnectorDelete,
rename to resourceConnectorVaultDelete.

2022-10-19 09:54 UTC, rathodmeetsatish commented
trigger build

2022-10-19 10:36 UTC, rijajoo approved these changes

2022-10-19 16:06 UTC, RajBaviskar approved these changes

2022-10-21 05:56 UTC, rashminandasahoo requested changes

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `aws_region` (String) This is the Aws region where aws iam auth will happen.
(String) AWS region where the AWS IAM authentication will happen.
AWS IAM

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `base_path` (String) This is the location of the Vault directory where Secret will be stored.
(String) Location of the Vault directory where the secret will be stored.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `auth_token` (String) This is the authentication token for Vault.
(String) Authentication token for Vault.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `k8s_auth_endpoint` (String) This is the path where kubernetes auth is enabled in Vault.
Kubernetes

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `namespace` (String) This is the Vault namespace where Secret will be created.
Vault namespace where the Secret will be created.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `renew_app_role_token` (Boolean) Boolean value to indicate if appRole token renewal is enabled or not.
AppRole

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `renewal_interval_minutes` (Number) This is the time interval for token renewal.
The time interval for the token renewal.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `service_account_token_path` (String) This is the SA token path where the token is mounted in the K8s Pod.
The Service Account token path in the K8s pod where the token is mounted.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `sink_path` (String) This is the location at which auth token is to be read from.
(String) The location from which the authentication token should be read.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `use_aws_iam` (Boolean) Boolean value to indicate if Aws Iam is used for authentication.
AWS IAM

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `use_k8s_auth` (Boolean) Boolean value to indicate if K8s Auth is used for authentication.
Why is the casing different? In some places, it is "auth" and in some, it is "Auth". Please make it consistent throughout.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_vault.md
> +- `vault_aws_iam_role` (String) This is the Vault role defined to bind to aws iam account/role being accessed.
Please correct the casing to AWS IAM everywhere.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_vault.md
> +  Resource for creating a Hashicorp Vault Secret Manager connector.
HashiCorp
This needs to be corrected everywhere.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_vault.md
> +- `renewal_interval_minutes` (Number) This is the time interval for token renewal.
We can start the sentence like this - "The time interval for the token renewal" and remove"This is"
This needs to be followed throughout. Refer to earlier comments.

2022-10-21 05:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_vault.md
> +- `aws_region` (String) This is the Aws region where aws iam auth will happen.
AWS
IAM

2022-10-21 05:56 UTC, rashminandasahoo commented on internal/service/platform/connector/vault_data_source.go
> +
Refer to previous comments for this section too.

2022-10-21 14:32 UTC, merged