CDS-44308-adding docs for gitops agents,clusters,apps,repos
harness/terraform-provider-harness pull request #272
Opened 2022-10-28 13:57 UTC by manavjot-harness

2022-10-29 17:14 UTC, rathodmeetsatish commented
trigger subcategoryfieldcheck

2022-11-04 05:49 UTC, rashminandasahoo requested changes
There are a few comments that must be applied throughout. So I have not put them at every line.
Example casing of the first word in a description; the consistent casing of "Id", Harness entities, etc.
Please check and do the changes in all the files.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/data-sources/platform_gitops_applications.md
> +- `generate_name` (String) an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will
An optional prefix that the server will only apply if the Name field is empty to create a unique name. The name returned to the client will differ from the name passed if this field is used. A unique suffix will be added to this value as well. The supplied value must adhere to the same validation guidelines as the Name field and may be reduced by the suffix length necessary to ensure that it is unique on the server. The server will NOT return a 409 if this field is supplied and the created name already exists; instead, it will either return 201 Created or 500 with Reason ServerTimeout, indicating that a unique name could not be found in the allotted time and the client should try again later.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/data-sources/platform_gitops_applications.md
> +- `generation` (String) A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
This is a read-only value populated by the system.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/data-sources/platform_gitops_applications.md
> +- `name` (String) Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automaticall
"Name cannot be updated."

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/data-sources/platform_gitops_cluster.md
> +- `account_id` (String) account identifier of the cluster.
The first letter must be capital. Please do this change through out.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/data-sources/platform_gitops_repository.md
> +- `creds_only` (Boolean) Whether to operate on credential set instead of repository.
Indicates if the operation must be on a credential set or repository.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/data-sources/platform_gitops_repository.md
> +- `id` (String) The ID of this resource.
Maintain a consistent casing of "ID". Please change this to "Id".

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_agent.md
> +- `identifier` (String) identifier for the gitops-agent.
Refer to previous comments.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_agent.md
> +- `name` (String) A human readable name for the gitops-agent.
Refer to previous comments.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_agent.md
> +- `description` (String) A human readable description for the gitops-agent
Refer to previous comments.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_agent.md
> +- `org_id` (String) Organization Identifier for the agent.
Organization identifier.
Project identifier

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_agent.md
> +- `high_availability` (Boolean) Whether or not this deployment should be deployed using deploy-ha.yaml
Indicates if this deployment should use deploy-ha.yaml

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_agent.md
> +- `namespace` (String) The k8s namespace that this agent resides in.
K8s namespace that corresponds to this agent.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_cluster.md
> +- `account_id` (String) account identifier of the cluster.
Refer to previous comments.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_cluster.md
> +- `org_id` (String) organization identifier of the cluster.
Correct the casing.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_cluster.md
> +- `project_id` (String) project identifier of the cluster.
Correct the casing here and in the rest of the places. Should start with capital letter.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_cluster.md
> +- `request` (Block List) Cluster create/Update request. (see [below for nested schema](#nestedblock--request))
create or update

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_cluster.md
> +- `name` (String) Name of the cluster. If omitted, will use the server address
end period missing

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_cluster.md
> +- `install_hint` (String) This text is shown to the user when the executable doesn't seem to be present
Message displayed when the executable is not found.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `enable_lfs` (Boolean) whether git-lfs support should be enabled for this repo. Only valid for Git repositories.
Indicates if git-lfs support must be enabled for this repo. This is valid only for Git repositories.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `org_id` (String) Organization Identifier for the Repository.
Check casing for this entire section.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `enable_oci` (Boolean) whether helm-oci support should be enabled for this repo
Indicates if helm-oci support must be enabled for this repo.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `github_app_enterprise_base_url` (String) the base URL of GitHub Enterprise installation. If empty will default to https://api.github.com
Base URL of GitHub Enterprise installation. If left empty, this defaults to https://api.github.com.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `github_app_installation_id` (String) the installation ID of the GitHub App used to access the repo.
Check casing

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `inherited_creds` (Boolean) Whether credentials were inherited from a credential set.
Indicates if the credentials were inherited from a credential set.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `insecure` (Boolean) specifies whether the connection to the repository ignores any errors when verifying TLS certificates or SSH host keys.
Indicates if the connection to the repository ignores any errors when verifying TLS certificates or SSH host keys.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `insecure_ignore_host_key` (Boolean) InsecureIgnoreHostKey should not be used anymore, Insecure is favoured Used only for Git repos.
Indicates if InsecureIgnoreHostKey should be used. Insecure is favored Used only for Git repos.

2022-11-04 05:49 UTC, rashminandasahoo commented on docs/resources/platform_gitops_repository.md
> +- `name` (String) name to be used for this repo. Only used with Helm repos.
Check casing for this and following lines.

2022-11-04 18:47 UTC, RajBaviskar approved these changes

2022-11-04 18:55 UTC, merged