[SPG-563]: Adding filters resource
harness/terraform-provider-harness pull request #273
Opened 2022-10-28 16:03 UTC by Y0709

2022-10-29 17:14 UTC, rathodmeetsatish commented
trigger subcategoryfieldcheck

2022-10-29 18:37 UTC, rathodmeetsatish commented on examples/data-sources/harness_platform_filters/data_source.tf
> +		  identifier  = "identifier"
cmd+s

2022-10-29 18:37 UTC, rathodmeetsatish commented on examples/resources/harness_platform_filters/resource.tf
> +			name = "name"
cmd + s

2022-10-29 18:39 UTC, rathodmeetsatish requested changes

2022-10-29 18:39 UTC, rathodmeetsatish commented on docs/data-sources/platform_filters.md
> +# generated by https://github.com/hashicorp/terraform-plugin-docs
@rashminandasahoo please review this

2022-10-29 18:42 UTC, rathodmeetsatish commented on internal/service/platform/filters/resource_filters_test.go
> +					resource.TestCheckResourceAttr(resourceName, "name", name),
please add some more assert statements here as well as in other places

2022-10-31 08:54 UTC, Y0709 commented on internal/service/platform/filters/resource_filters_test.go
> +					resource.TestCheckResourceAttr(resourceName, "name", name),
done

2022-10-31 09:53 UTC, rijajoo approved these changes

2022-10-31 10:47 UTC, rashminandasahoo requested changes

2022-10-31 10:47 UTC, rashminandasahoo commented on docs/resources/platform_filters.md
> +- `org_id` (String) Organization Identifier for the Entity
Make the casing to "organization" and "project" every where

2022-10-31 11:41 UTC, Y0709 commented on docs/data-sources/platform_filters.md
> +  type       = "Connector"
This we cant change as it an enum . It will work only for "Connector" not "connector"

2022-10-31 11:41 UTC, Y0709 commented on docs/resources/platform_filters.md
> +  type       = "Connector"
This we cant change as it an enum . It will work only for "Connector" not "connector"

2022-10-31 11:44 UTC, Y0709 commented on docs/resources/platform_filters.md
> +    filter_type = "Connector"
This we cant change as it an enum . It will work only for "Connector" not "connector"

2022-10-31 13:55 UTC, rathodmeetsatish approved these changes

2022-10-31 15:28 UTC, rashminandasahoo approved these changes

2022-10-31 15:32 UTC, merged