Create azure cloud provider connector
harness/terraform-provider-harness pull request #274
Opened 2022-10-29 13:29 UTC by rathodmeetsatish

Create azure cloud provider connector

2022-10-29 15:11 UTC, rathodmeetsatish commented
trigger subcategoryfieldcheck

2022-10-29 15:12 UTC, rathodmeetsatish commented
trigger subcategoryfieldcheck

2022-10-31 12:14 UTC, rashminandasahoo requested changes

2022-10-31 12:14 UTC, rashminandasahoo commented on internal/service/platform/connector/azure_cloud_provider_data_source.go
> +				Description: "Specifies the Azure Environment type, which is AZURE by default.Can either be AZURE or AZURE_US_GOVERNMENT",
Space missing after end period (default. Can).

2022-10-31 12:14 UTC, rashminandasahoo commented on internal/service/platform/connector/azure_cloud_provider_test.go
> +			description = "test"
Let us replace "test" with "example" every where.

2022-11-02 04:54 UTC, rashminandasahoo approved these changes

2022-11-02 04:54 UTC, merged