Add azure cloud cost connector
harness/terraform-provider-harness pull request #284
Opened 2022-11-04 22:14 UTC by rathodmeetsatish

## Describe your changes
Add azure cloud cost connector

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2022-11-07 08:40 UTC, rijajoo approved these changes

2022-11-08 01:22 UTC, RajBaviskar approved these changes

2022-11-10 07:56 UTC, rashminandasahoo requested changes

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_azure_cloud_cost.md
> +- `id` (String) The ID of this resource.
Id of the resource.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_azure_cloud_cost.md
> +- `tags` (Set of String) Tags to associate with the resource. Tags should be in the form `name:value`.
Tags to use for the resource. Tags should be in the form `name:value`.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `billing_export_spec` (Block List, Max: 1) Returns Billing details like StorageAccount's Name, container's Name, directory's Name, report Name and subscription Id. (see [below for nested schema](#n
Refer to the previous comments.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `org_id` (String) Unique identifier of the Organization.
Refer to the previous comments.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `project_id` (String) Unique identifier of the Project.
Refer to the previous comments.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `tags` (Set of String) Tags to associate with the resource. Tags should be in the form `name:value`.
Refer to the previous comments.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `container_name` (String) Container Name.
Name of the container.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `directory_name` (String) Directory Name.
Name of the directory.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `report_name` (String) Report Name.
Name of the report.

2022-11-10 07:56 UTC, rashminandasahoo commented on docs/resources/platform_connector_azure_cloud_cost.md
> +- `storage_account_name` (String) Storage Account Name.
Name of the storage account.

2022-11-10 17:22 UTC, rathodmeetsatish commented on docs/data-sources/platform_connector_azure_cloud_cost.md
> +- `org_id` (String) Unique identifier of the Organization.
you suggested o should be capital in one of earlier pr

2022-11-10 17:22 UTC, rathodmeetsatish commented on docs/data-sources/platform_connector_azure_cloud_cost.md
> +- `project_id` (String) Unique identifier of the Project.
you suggested p should be capital in one of earlier pr

2022-11-11 04:02 UTC, rashminandasahoo approved these changes

2022-11-11 07:04 UTC, merged