Add gcp cloud cost connector
harness/terraform-provider-harness pull request #285
Opened 2022-11-04 23:36 UTC by rathodmeetsatish

## Describe your changes
Add gcp cloud cost connector

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2022-11-07 08:32 UTC, rijajoo commented on docs/data-sources/platform_connector_gcp_cloud_cost.md
> +  Datasource for looking up an GCP Cloud Cost Connector.
a*

2022-11-07 08:32 UTC, rijajoo commented on docs/data-sources/platform_connector_gcp_cloud_cost.md
> +Datasource for looking up an GCP Cloud Cost Connector.
Please review all places it says an GCP

2022-11-08 01:22 UTC, RajBaviskar approved these changes

2022-11-09 11:21 UTC, rashminandasahoo requested changes

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_gcp_cloud_cost.md
> +- `features_enabled` (Set of String) Which feature to enable among BILLING, OPTIMIZATION, VISIBILITY
Indicates which features to enable among Billing, Optimization, and Visibility.
Can multiple features be enabled?

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_gcp_cloud_cost.md
> +- `id` (String) The ID of this resource.
Id of the resource.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_gcp_cloud_cost.md
> +- `service_account_email` (String) Service Account Email.
Email corresponding to the Service Account.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_gcp_cloud_cost.md
> +- `tags` (Set of String) Tags to associate with the resource. Tags should be in the form `name:value`.
Tags to use for the resource. Tags should be in the form `name:value`.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/resources/platform_connector_gcp_cloud_cost.md
> +- `features_enabled` (Set of String) Which feature to enable among BILLING, OPTIMIZATION, VISIBILITY
Refer to the previous comment.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/resources/platform_connector_gcp_cloud_cost.md
> +- `service_account_email` (String) Service Account Email.
Refer to the previous comment.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/resources/platform_connector_gcp_cloud_cost.md
> +- `billing_export_spec` (Block List, Max: 1) Returns Billing details. (see [below for nested schema](#nestedblock--billing_export_spec))
Returns billing details.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/resources/platform_connector_gcp_cloud_cost.md
> +- `org_id` (String) Unique identifier of the Organization.
Unique identifier of the organization.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/resources/platform_connector_gcp_cloud_cost.md
> +- `project_id` (String) Unique identifier of the Project.
Unique identifier of the project.

2022-11-09 11:21 UTC, rashminandasahoo commented on docs/resources/platform_connector_gcp_cloud_cost.md
> +- `tags` (Set of String) Tags to associate with the resource. Tags should be in the form `name:value`.
Refer to the previous comments.

2022-11-11 10:58 UTC, rashminandasahoo approved these changes

2022-11-11 11:23 UTC, merged