Add kubernetes cloud cost connector
harness/terraform-provider-harness pull request #286
Opened 2022-11-05 06:28 UTC by rathodmeetsatish

## Describe your changes
Add kubernetes cloud cost connector

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2022-11-07 08:30 UTC, rijajoo commented on docs/data-sources/platform_connector_kubernetes_cloud_cost.md
> +- `connector_ref` (String) Referenve of the Connector.
Reference*

2022-11-07 08:30 UTC, rijajoo commented on docs/resources/platform_connector_kubernetes_cloud_cost.md
> +- `connector_ref` (String) Referenve of the Connector.
*Reference

2022-11-08 01:18 UTC, RajBaviskar commented on docs/resources/platform_connector_kubernetes_cloud_cost.md
> +  description = "example"
minor: can be instead of "example" can be "description"

2022-11-08 01:19 UTC, RajBaviskar commented on docs/resources/platform_connector_kubernetes_cloud_cost.md
> +- `tags` (Set of String) Tags to associate with the resource. Tags should be in the form `name:value`.
it doesn't need to be name:value

2022-11-08 01:20 UTC, RajBaviskar approved these changes

2022-11-10 11:28 UTC, rashminandasahoo requested changes

2022-11-10 11:28 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_kubernetes_cloud_cost.md
> +- `org_id` (String) Unique identifier of the Organization.
Unique identifier of the organization.

2022-11-10 11:28 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_kubernetes_cloud_cost.md
> +- `project_id` (String) Unique identifier of the Project.
Unique identifier of the project.

2022-11-10 11:28 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_kubernetes_cloud_cost.md
> +- `features_enabled` (Set of String) Which feature to enable among BILLING, OPTIMIZATION, VISIBILITY
Indicates which feature to enable among Billing, Optimization, and Visibility.

2022-11-10 11:28 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_kubernetes_cloud_cost.md
> +- `tags` (Set of String) Tags to associate with the resource. Tags should be in the form `name:value`.
Tags to use for the resource. Tags should be in the form `name:value`.

2022-11-10 11:28 UTC, rashminandasahoo commented on docs/resources/platform_connector_kubernetes_cloud_cost.md
> +- `org_id` (String) Unique identifier of the Organization.
Refer to the previous comments.

2022-11-11 03:25 UTC, rathodmeetsatish commented on docs/resources/platform_connector_kubernetes_cloud_cost.md
> +  description = "example"
Rashmi has asked to use example in example usage

2022-11-11 10:42 UTC, rathodmeetsatish commented
trigger build

2022-11-11 10:58 UTC, rashminandasahoo approved these changes

2022-11-11 10:59 UTC, merged