add azure key vault resource
harness/terraform-provider-harness pull request #287
Opened 2022-11-07 13:00 UTC by rathodmeetsatish

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2022-11-17 13:54 UTC, rijajoo requested changes

2022-11-17 13:54 UTC, rijajoo commented on internal/service/platform/connector/azure_key_vault_data_source.go
> +				Description: "Connect using only the delegates which have these tags.",
Please check the other delegate_selectors descriptions updated.

2022-11-22 10:13 UTC, deepakbolangady commented on .changelog/287.txt
> +platform_connector_azure_key_vault - Added Azure Key Vault connector resource in Harness terraform provider
Minor corrections: Added the Azure Key Vault connector resource to the Harness terraform provider.

2022-11-22 10:15 UTC, deepakbolangady commented on docs/data-sources/platform_connector_azure_key_vault.md
> +subcategory: "Next Gen"
NextGen (one word)

2022-11-22 10:18 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +  Resource for creating an Azure Key Vault in Harness.
Unless we are describing the feature (Azure Key Vault), no need to use upper case for "key vault". So this would be "Azure key vault".

2022-11-22 10:50 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +- `subscription` (String) Azure Subscription ID.
Global, if applicable: "Azure subscription ID" (no need to capitalize "s")

2022-11-22 10:51 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +- `client_id` (String) Application ID of the Azure App.
Can we add clarity to the term "Azure App"? Please reach out if you have any questions about this comment.

2022-11-22 10:58 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +- `azure_environment_type` (String) Specifies the Azure Environment type, which is AZURE by default. Can either be AZURE or AZURE_US_GOVERNMENT
Don't need "Specifies the", just for consistency with other descriptions.
Also, lower case "e" in "environment". 
Finally, "can be either" (parallelism within the sentence). 

Can we use this format everywhere?
`azure_environment_type` (String) Azure environment type. Possible values: AZURE or AZURE_US_GOVERNMENT. Default value: AZURE

2022-11-22 11:01 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +- `delegate_selectors` (Set of String) Connect using only the delegates which have these tags.
Can we write "Set of strings"?
Also, replace "which" with "that".
What do we mean by "these tags"? Most users might get this, but we need to write for the one that might not.

2022-11-22 11:04 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +- `org_id` (String) Unique identifier of the Organization.
lower case "o" in organization.

2022-11-22 11:05 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +- `project_id` (String) Unique identifier of the Project.
lower case "p" in project

2022-11-22 11:05 UTC, deepakbolangady commented on docs/resources/platform_connector_azure_key_vault.md
> +- `id` (String) The ID of this resource.
Remove "the" for consistency with other descriptions.

2022-11-22 11:07 UTC, deepakbolangady commented on internal/service/platform/connector/azure_key_vault_data_source.go
> +		Description: "Datasource for looking up an Azure Cloud Provider Connector.",
Data source is two words? Is there a reason for merging them?

2022-11-22 11:09 UTC, deepakbolangady requested changes
Added corrections and questions to descriptions. Please reach out if you have questions. Thanks.

2022-11-23 11:24 UTC, rathodmeetsatish commented on docs/resources/platform_connector_azure_key_vault.md
> +- `azure_environment_type` (String) Specifies the Azure Environment type, which is AZURE by default. Can either be AZURE or AZURE_US_GOVERNMENT
yes

2022-11-23 11:25 UTC, rathodmeetsatish commented on docs/resources/platform_connector_azure_key_vault.md
> +- `org_id` (String) Unique identifier of the Organization.
org_id is common field will fix in separate pr

2022-11-23 11:26 UTC, rathodmeetsatish commented on docs/resources/platform_connector_azure_key_vault.md
> +- `project_id` (String) Unique identifier of the Project.
project_id is common field will fix in separate pr

2022-11-23 11:26 UTC, rathodmeetsatish commented on docs/resources/platform_connector_azure_key_vault.md
> +- `id` (String) The ID of this resource.
id is common field will fix in separate pr

2022-11-23 11:26 UTC, rathodmeetsatish commented on docs/resources/platform_connector_azure_key_vault.md
> +- `vault_name` (String) The Azure Active Directory (AAD) directory ID where you created your application.
done

2022-11-23 11:27 UTC, rathodmeetsatish commented on docs/resources/platform_connector_azure_key_vault.md
> +- `client_id` (String) Application ID of the Azure App.
done

2022-11-23 11:27 UTC, rathodmeetsatish commented on docs/data-sources/platform_connector_azure_key_vault.md
> +subcategory: "Next Gen"
Its a common field will discuss and change everywhere

2022-11-23 13:16 UTC, deepakbolangady commented on .changelog/287.txt
> +platform_connector_azure_key_vault - Added the Azure Key Vault connector resource to the Harness terraform provider.
This is my bad, Meet. Can we please change terraform to Terraform globally, in descriptive text? Thanks and sorry for the miss.

2022-11-23 13:16 UTC, deepakbolangady commented on docs/data-sources/platform_connector_azure_key_vault.md
> +page_title: "harness_platform_connector_azure_key_vault Data Source - terraform-provider-harness"
"data source" (no caps unless "data" begins a sentence)

2022-11-23 13:18 UTC, deepakbolangady commented on docs/data-sources/platform_connector_azure_key_vault.md
> +  Data Source for looking up an Azure key vault Connector.
"connector" is another one of those words that should not be init-capped.

2022-11-23 13:31 UTC, deepakbolangady approved these changes
Approving the changes with a note to incorporate the capitalization issues in some descriptions. Please incorporate and then proceed.

Also noting that the descriptions have not been corrected because they have been brought in from the API docs at apidocs.harness.io. We need to develop a process to review the API and bring those reviewed descriptions to the Terraform provider docs.

2022-11-23 19:11 UTC, rathodmeetsatish commented on .changelog/287.txt
> +platform_connector_azure_key_vault - Added the Azure Key Vault connector resource to the Harness terraform provider.
done

2022-11-23 19:12 UTC, rathodmeetsatish commented on docs/data-sources/platform_connector_azure_key_vault.md
> +page_title: "harness_platform_connector_azure_key_vault Data Source - terraform-provider-harness"
done

2022-11-24 05:27 UTC, rijajoo approved these changes

2022-11-24 05:28 UTC, merged