[SPG: 477]: Add docs to specify the identifier of secret refs
harness/terraform-provider-harness pull request #293
Opened 2022-11-09 15:19 UTC by rijajoo

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2022-11-09 17:06 UTC, RajBaviskar approved these changes

2022-11-15 05:54 UTC, rashminandasahoo requested changes
I gave a quick look through the files. Please follow the template for all the secret reference, throughout. 
All other comments need to be implemented throughout as well.

2022-11-15 05:54 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_pagerduty.md
>  - `delegate_selectors` (Set of String) Connect using only the delegates which have these tags.
Refer to the previous comments and follow the same template.

2022-11-15 05:54 UTC, rashminandasahoo commented on docs/data-sources/platform_connector_prometheus.md
>  - `url` (String) Url of the Prometheus server.
URL

2022-11-17 10:11 UTC, rashminandasahoo approved these changes

2022-11-17 10:31 UTC, merged