[SPG-823]: adding pipeline filters TF resource
harness/terraform-provider-harness pull request #307
Opened 2022-11-18 21:45 UTC by RajBaviskar

## Describe your changes

- adding pipeline filters TF resource

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2022-11-21 18:59 UTC, rathodmeetsatish commented on internal/service/platform/pipeline_filters/resource_pipeline_filters.go
> +				ValidateFunc: validation.StringInSlice([]string{"Connector", "DelegateProfile", "Delegate", "PipelineSetup", "PipelineExecution", "Deployment", "Audit", "Template", "EnvironmentGroup", "FileStore
for pipeline filters i guess all these types wont be valid like connector or audit similarly in data source

2022-11-21 18:59 UTC, rathodmeetsatish commented on internal/service/platform/pipeline_filters/resource_pipeline_filters.go
> +							ValidateFunc: validation.StringInSlice([]string{"Connector", "DelegateProfile", "Delegate", "PipelineSetup", "PipelineExecution", "Deployment", "Audit", "Template", "EnvironmentGroup", "FileSt
same as above

2022-11-21 23:44 UTC, RajBaviskar commented on internal/service/platform/pipeline_filters/resource_pipeline_filters.go
> +				ValidateFunc: validation.StringInSlice([]string{"Connector", "DelegateProfile", "Delegate", "PipelineSetup", "PipelineExecution", "Deployment", "Audit", "Template", "EnvironmentGroup", "FileStore
updated

2022-11-21 23:44 UTC, RajBaviskar commented on internal/service/platform/pipeline_filters/resource_pipeline_filters.go
> +							ValidateFunc: validation.StringInSlice([]string{"Connector", "DelegateProfile", "Delegate", "PipelineSetup", "PipelineExecution", "Deployment", "Audit", "Template", "EnvironmentGroup", "FileSt
updated

2022-11-22 06:39 UTC, rijajoo requested changes

2022-11-22 06:39 UTC, rijajoo commented on internal/service/platform/pipeline_filters/data_source_pipeline_filters.go
> +				Description: "Unique identifier of the resource",
Please add full stops (.) at the end of every description sentence.

2022-11-22 06:39 UTC, rijajoo commented on internal/service/platform/pipeline_filters/data_source_pipeline_filters.go
> +				Description: "organization Identifier for the Entity",
Please check that sentences start with Capital case.

2022-11-22 20:08 UTC, RajBaviskar commented on internal/service/platform/pipeline_filters/data_source_pipeline_filters.go
> +				Description: "organization Identifier for the Entity",
changed.

2022-11-22 20:10 UTC, merged

2022-11-23 15:16 UTC, Clare-Wilkinson reviewed
Thanks for sending - a few small things just :)

2022-11-23 15:16 UTC, Clare-Wilkinson commented on docs/resources/platform_pipeline_filters.md
> +Resource for creating a Harness Pipeline Filters.
As above, please remove "a" from before Harness.