Update api key fields documentation
harness/terraform-provider-harness pull request #324
Opened 2022-11-29 02:54 UTC by rathodmeetsatish

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2022-11-29 04:41 UTC, rashminandasahoo requested changes

2022-11-29 04:41 UTC, rashminandasahoo commented on docs/index.md
>  - `account_id` (String) The Harness account id. This can also be set using the `HARNESS_ACCOUNT_ID` environment variable.
Harness account id. You can fetch this value from the environment variable HARNESS_ACCOUNT_ID.

2022-11-29 04:41 UTC, rashminandasahoo commented on docs/index.md
> +- `api_key` (String) The Harness API key. This can also be set using the `HARNESS_API_KEY` environment variable. To create an api key in firstgen follow this doc https://docs.harness.io/article/smloy
Harness API key. You can fetch this value from the environment variable HARNESS_API_KEY.
Casing -> FirstGen. 
For more information to create an API key in FirstGen, see [Create an API Key](https://docs.harness.io/article/smloyragsm-api-keys#create_an_api_key).

2022-11-29 04:41 UTC, rashminandasahoo commented on docs/index.md
>  - `endpoint` (String) The URL of the Harness API endpoint. The default is `https://app.harness.io/gateway`. This can also be set using the `HARNESS_ENDPOINT` environment variable.
URL of the Harness API endpoint. The default endpoint URL is `https://app.harness.io/gateway`. You can fetch this from the environment variable `HARNESS_ENDPOINT`

2022-11-29 04:41 UTC, rashminandasahoo commented on docs/index.md
> +- `platform_api_key` (String) The API key for the Harness next gen platform. This can also be set using the `HARNESS_PLATFORM_API_KEY` environment variable. To create an api key in nextgen follow thi
API key for Harness NextGen. You can fetch this from the environment variable `HARNESS_PLATFORM_API_KEY`. For more information to create an API key in NextGen, see [Create an API Key](https://docs.harness.io/article/tdoad7xrh9-add-and-manage-api-keys).

2022-11-29 04:46 UTC, rathodmeetsatish commented on docs/index.md
>  - `account_id` (String) The Harness account id. This can also be set using the `HARNESS_ACCOUNT_ID` environment variable.
You can fetch this value from the environment variable HARNESS_ACCOUNT_ID.
this has different meaning than original text we are not trying to fetch account_id we are trying to set it similarly in other comments

2022-11-29 05:28 UTC, rashminandasahoo commented on docs/index.md
>  - `account_id` (String) The Harness account id. This can also be set using the `HARNESS_ACCOUNT_ID` environment variable.
Ok, then we can retain the original sentence (`This can also be set using the `HARNESS_ACCOUNT_ID` environment variable.`).

2022-12-06 05:02 UTC, rashminandasahoo approved these changes

2022-12-06 05:03 UTC, merged