CDS-53904 making org and project optional
harness/terraform-provider-harness pull request #436
Opened 2023-02-22 01:10 UTC by RajBaviskar

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-02-22 06:40 UTC, rathodmeetsatish commented on docs/resources/platform_environment.md
>  - `description` (String) Description of the resource.
import examples are not reflecting in doc and please add org level and account level examples

2023-02-22 06:40 UTC, rathodmeetsatish commented on docs/resources/platform_service.md
import examples are not reflecting in doc and please add org level and account level examples

2023-02-22 06:40 UTC, rathodmeetsatish commented on docs/data-sources/platform_environment.md
>  - `identifier` (String) Unique identifier of the resource.
identifier should be required right?

2023-02-22 06:40 UTC, rathodmeetsatish commented on docs/data-sources/platform_service.md
>  - `identifier` (String) Unique identifier of the resource.
identifier should be required right?

2023-02-22 06:42 UTC, rathodmeetsatish requested changes

2023-02-22 06:42 UTC, rathodmeetsatish commented on internal/service/platform/service/resource_service_test.go
> +					resource.TestCheckResourceAttr(resourceName, "name", updatedName),
can we assert org_id similarly in other places

2023-02-23 05:36 UTC, RajBaviskar commented on docs/data-sources/platform_environment.md
>  - `identifier` (String) Unique identifier of the resource.
changed.

2023-02-23 05:36 UTC, RajBaviskar commented on docs/data-sources/platform_service.md
>  - `identifier` (String) Unique identifier of the resource.
changed.

2023-02-23 05:39 UTC, RajBaviskar commented on docs/resources/platform_environment.md
>  - `description` (String) Description of the resource.
added.

2023-02-23 05:39 UTC, RajBaviskar commented on docs/resources/platform_service.md
added.

2023-02-23 05:40 UTC, RajBaviskar commented on internal/service/platform/service/resource_service_test.go
> +					resource.TestCheckResourceAttr(resourceName, "name", updatedName),
added

2023-02-23 08:41 UTC, rathodmeetsatish approved these changes

2023-02-23 08:47 UTC, merged