Pl 31585
harness/terraform-provider-harness pull request #446
Opened 2023-02-27 17:54 UTC by rijajoo

## Describe your changes

Fixed User Resource

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-02-27 20:12 UTC, RajBaviskar approved these changes

2023-02-28 04:02 UTC, rathodmeetsatish requested changes
Please add examples

2023-02-28 04:02 UTC, rathodmeetsatish commented on internal/acctest/acctest.go
> +		return fmt.Sprintf("%s/%s/%s/%s", orgId, projId, email, id), nil
when we are asking for email we wont need to ask for id

2023-02-28 04:03 UTC, rathodmeetsatish requested changes
add examples

2023-02-28 09:24 UTC, rijajoo commented
trigger subcategoryfieldcheck

2023-02-28 11:38 UTC, rathodmeetsatish commented
trigger build

2023-02-28 11:38 UTC, rathodmeetsatish commented
trigger subcategoryfieldcheck

2023-02-28 13:36 UTC, rathodmeetsatish commented
trigger subcategoryfieldcheck

2023-02-28 14:05 UTC, rijajoo commented
trigger build

2023-02-28 14:10 UTC, merged