[CDS-54856]: Adding OCI helm go files manual changes
harness/terraform-provider-harness pull request #466
Opened 2023-03-10 13:18 UTC by namantalaycha10

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-03-10 14:01 UTC, rathodmeetsatish requested changes

2023-03-13 13:04 UTC, namantalaycha10 commented on examples/data-sources/harness_platform_connector_oci_helm/data-source.tf
> +data "harness_platform_connector_oic_helm" "example" {
Done

2023-03-13 13:04 UTC, namantalaycha10 commented on examples/resources/harness_platform_connector_oci_helm/resource.tf
> +# Credential username_password
Done

2023-03-13 13:04 UTC, namantalaycha10 commented on internal/service/platform/connector/oci_helm_test.go
> +	resourceName := "harness_platform_connector_helm.test"
Done

2023-03-13 13:04 UTC, namantalaycha10 commented on internal/service/platform/connector/oci_helm_test.go
> +	resourceName := "harness_platform_connector_helm.test"
Done

2023-03-13 13:04 UTC, namantalaycha10 commented on internal/service/platform/connector/oci_helm_data_source_test.go
> +		resource "harness_platform_connector_helm" "test" {
Done

2023-03-13 13:04 UTC, namantalaycha10 commented on internal/service/platform/connector/oci_helm_data_source_test.go
> +		resourceName = "data.harness_platform_connector_helm.test"
Done

2023-03-13 13:04 UTC, namantalaycha10 commented on .changelog/458.txt
> +```release-note:new-data-source
Done

2023-03-13 13:04 UTC, namantalaycha10 commented on .changelog/458.txt
> +```release-note:new-resource
Done

2023-03-13 13:50 UTC, namantalaycha10 commented
trigger build

2023-03-13 13:50 UTC, namantalaycha10 commented
trigger subcategoryfieldcheck

2023-03-13 17:53 UTC, namantalaycha10 commented
trigger build

2023-03-14 06:19 UTC, rathodmeetsatish approved these changes

2023-03-14 06:19 UTC, merged