[CDS-57817] : have added terraform support force deletion of for services/env/template
harness/terraform-provider-harness pull request #491
Opened 2023-03-27 11:44 UTC by vivekkarnatiharness

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-03-28 09:16 UTC, rathodmeetsatish requested changes
as there is an addition in schema please genrate docs and add a file file in .changelog folder corresponding to your pr number

2023-03-28 09:16 UTC, rathodmeetsatish commented on internal/service/platform/environment/resource_environment.go
> +			"forcedelete": {
according to naming convention we are following it should be force_delete

2023-03-28 09:16 UTC, rathodmeetsatish commented on internal/service/platform/environment_group/resource_environment_group.go
> +			"forcedelete": {
same as above

2023-03-28 09:16 UTC, rathodmeetsatish commented on internal/service/platform/service/resource_service.go
> +				Type:        schema.TypeString,
same as above

2023-03-28 12:20 UTC, vivekkarnatiharness commented on internal/service/platform/environment_group/resource_environment_group.go
> +			"forcedelete": {
done

2023-03-28 12:20 UTC, vivekkarnatiharness commented on internal/service/platform/service/resource_service.go
> +				Type:        schema.TypeString,
done

2023-03-28 15:06 UTC, rathodmeetsatish approved these changes

2023-03-28 15:45 UTC, yogesh-chauhan requested changes

2023-03-28 15:45 UTC, yogesh-chauhan commented on helpers/schema.go
> +		return optional.NewBool(arr.(string) == var1)
can we not do this directly like 

"true" == arr.(string)

2023-03-28 15:46 UTC, vivekkarnatiharness commented on helpers/schema.go
> +		return optional.NewBool(arr.(string) == var1)
No,i am getting syntax error,That untyped variable cant be compared with a typed variable

2023-03-28 16:06 UTC, vivekkarnatiharness commented on internal/service/platform/environment/resource_environment.go
> +				Description: "Enable this flag for force deletion of environments",
done

2023-03-28 16:53 UTC, yogesh-chauhan approved these changes

2023-03-29 05:13 UTC, rathodmeetsatish approved these changes

2023-03-29 05:14 UTC, merged