Fixed Delete Underlying Resource Test
harness/terraform-provider-harness pull request #505
Opened 2023-04-06 08:52 UTC by adiyaar24

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-04-06 13:57 UTC, rijajoo requested changes

2023-04-06 13:57 UTC, rijajoo commented on internal/service/platform/user/resource_user_test.go
> +					myInt, _ := testGetUserUUID(email,id,id)
rename myInt and reformat all files.

2023-04-06 15:22 UTC, adiyaar24 commented on internal/service/platform/user/resource_user_test.go
> +					myInt, _ := testGetUserUUID(email,id,id)
Done

2023-04-07 13:33 UTC, rijajoo approved these changes

2023-04-07 13:41 UTC, merged