Cds 54508
harness/terraform-provider-harness pull request #508
Opened 2023-04-13 10:19 UTC by tmacari-harness

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-04-18 12:31 UTC, tmacari-harness commented
trigger subcategoryfieldcheck

2023-04-22 11:09 UTC, deepakbolangady submitted a review, later dismissed
Approving with the understanding that you will incorporate the changes. Let me know if an approval is required again. Thank you.

2023-04-22 11:09 UTC, deepakbolangady commented on docs/resources/platform_connector_terraform_cloud.md
> +- `api_token` (Block List, Min: 1, Max: 1) API token credentials to use for authentication. (see [below for nested schema](#nestedblock--credentials--api_token))
```suggestion
- `api_token` (Block List, Min: 1, Max: 1) API token credentials to use for authentication. (See [below for nested schema](#nestedblock--credentials--api_token).)
```

2023-04-22 11:09 UTC, deepakbolangady commented on docs/resources/platform_connector_terraform_cloud.md
> +- `api_token_ref` (String) Reference to a secret containing the api token to use for authentication. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}.
```suggestion
- `api_token_ref` (String) Reference to a secret containing the API token to use for authentication. To reference a secret at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference a secret at the account scope, prefix 'account` to the expression: account.{identifier}.
```

2023-04-22 11:09 UTC, deepakbolangady commented on docs/resources/platform_connector_terraform_cloud.md
> +# Import using terrafrm cloud provider connector id
```suggestion
# Import using the Terraform Cloud provider connector ID.
```

2023-04-22 11:09 UTC, deepakbolangady commented on examples/resources/harness_platform_connector_terraform_cloud/resource.tf
> +# Create Terraform Cloud connector using API token as secret
Same comment about "using" (either write "by using" or "that uses", depending on which one is accurate.

2023-04-22 11:09 UTC, deepakbolangady commented on examples/resources/harness_platform_connector_terraform_cloud/import.sh
> +# Import using terrafrm cloud provider connector id
```suggestion
# Import using the Terraform Cloud provider connector ID.
```

2023-04-22 11:09 UTC, deepakbolangady commented on examples/resources/harness_platform_connector_terraform_cloud/resource.tf
> +# Add connectivity mode by providing execute_on_delegate value. Default is to execute on Delegate
Same as earlier.

2023-04-22 11:09 UTC, deepakbolangady commented on internal/service/platform/connector/terraform_cloud.go
> +		Description:   "Resource for creating a TerraformCloud connector.",
```suggestion
		Description:   "Resource for creating a Terraform Cloud connector.",
```

2023-04-22 11:09 UTC, deepakbolangady commented on internal/service/platform/connector/terraform_cloud.go
> +				Description: "URL of Terraform Cloud platform.",
```suggestion
				Description: "URL of the Terraform Cloud platform.",
```

2023-04-22 11:09 UTC, deepakbolangady commented on internal/service/platform/connector/terraform_cloud.go
> +				Description: "Credentials to connect to Terraform Cloud platform.",
```suggestion
				Description: "Credentials to connect to the Terraform Cloud platform.",
```

2023-04-22 11:09 UTC, deepakbolangady commented on internal/service/platform/connector/terraform_cloud.go
> +				Description: "Credentials to connect to Terraform Cloud platform.",
It looks like the text beyond this point is the same as the text I've already commented on. Please incorporate as necessary. I'll end my review here. Thank you.

2023-04-25 11:44 UTC, tmacari-harness commented
Hi @deepakbolangady, the above docs were generated automatically by a tool.
@micahlmartin should we stick to generated docs or we can adjust them?
cc @rathodmeetsatish

2023-04-26 08:02 UTC, tmacari-harness commented on docs/resources/platform_connector_terraform_cloud.md
> +subcategory: "Next Gen"
This cant be changed now

2023-04-26 08:02 UTC, tmacari-harness commented on docs/data-sources/platform_connector_terraform_cloud.md
> +- `api_token` (List of Object) (see [below for nested schema](#nestedobjatt--credentials--api_token))
Those are changes done by docs autogenerating tool

2023-04-26 08:42 UTC, rathodmeetsatish requested changes

2023-04-26 08:42 UTC, rathodmeetsatish commented on internal/service/platform/connector/terraform_cloud_test.go
> +
please add a test similar to TestAccResourceConnectorJenkins_DeleteUnderlyingResource.
It is to test scenario when someone creates a resource via terraform but deletes it from ui and again applys from terraform then it should not error out but should create a new resource

2023-04-26 10:42 UTC, tmacari-harness commented on internal/service/platform/connector/terraform_cloud_test.go
> +
Done

2023-04-26 10:58 UTC, rathodmeetsatish approved these changes

2023-04-26 10:59 UTC, merged