Updated Test For Connectors
harness/terraform-provider-harness pull request #509
Opened 2023-04-17 05:49 UTC by adiyaar24

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-05-02 17:40 UTC, rathodmeetsatish commented
trigger build

2023-05-02 17:41 UTC, rathodmeetsatish commented
trigger subcategoryfieldcheck

2023-05-05 13:18 UTC, rijajoo requested changes

2023-05-05 13:18 UTC, rijajoo commented on .changelog/509.txt
> +resources/platform_secret_sshkey: Updated the Behaviour of referening the secrets at account,project and org Level . Made Key Field Required in SSH credential of type keyReference
Lots of typos. Please fix this.

2023-05-05 13:18 UTC, rijajoo commented on internal/service/platform/connector/vault_test.go
> +		create_duration = "10s"
Why are we updating the time here? Also why is it still called wait_4_seconds? This is misleading.

2023-05-11 13:14 UTC, rijajoo approved these changes

2023-05-11 13:14 UTC, rijajoo commented on .changelog/509.txt
> +resources/platform_role_assignments: Made resource_group_identifier, role_identifier and type under principle schema required.
principal*

2023-05-11 13:45 UTC, rijajoo approved these changes

2023-05-11 13:45 UTC, rijajoo approved these changes

2023-05-11 15:38 UTC, merged