feat: [CDS-56975]: Add quarterly recurrence support for deployment freeze
harness/terraform-provider-harness pull request #522
Opened 2023-04-27 05:40 UTC by RishabhGupta34

## Describe your changes
Add quarterly recurrence support for deployment freeze

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-05-02 13:43 UTC, rathodmeetsatish requested changes
Add a file in .changelog folder to describe the changes done in this pr

2023-05-02 13:43 UTC, rathodmeetsatish commented on docs/data-sources/platform_manual_freeze.md
> +- `value` (Number)
description is not appearing for the fields

2023-05-02 13:43 UTC, rathodmeetsatish commented on docs/resources/platform_manual_freeze.md
> +- `value` (Number)
description is not appearing for the fields

2023-05-03 12:38 UTC, RishabhGupta34 commented on docs/data-sources/platform_manual_freeze.md
> +- `value` (Number)
added

2023-05-04 12:45 UTC, rathodmeetsatish requested changes

2023-05-04 12:45 UTC, rathodmeetsatish commented on docs/data-sources/platform_manual_freeze.md
> +- `until` (String) Recurrence until timestamp
descriptions are still not reflect for all the fields

2023-05-04 12:45 UTC, rathodmeetsatish commented on .changelog/528.txt
> +```release-note:enhancement
file name should be same as pr number

2023-05-05 08:11 UTC, RishabhGupta34 commented on docs/resources/platform_manual_freeze.md
> +- `until` (String) Recurrence until timestamp
done

2023-05-05 08:15 UTC, rathodmeetsatish approved these changes

2023-05-05 08:40 UTC, merged