feat: [CDS-57560]: Added support for TAS
harness/terraform-provider-harness pull request #523
Opened 2023-04-27 05:41 UTC by RishabhGupta34

## Describe your changes
Added support for TAS connector and infrastructure in NG

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-05-02 13:40 UTC, rathodmeetsatish requested changes
Add a file in .changelog folder corresponding to this pr number and add content similar to 517.txt

2023-05-02 13:40 UTC, rathodmeetsatish commented on docs/data-sources/platform_connector_tas.md
> +
data source example is not reflecting in docs

2023-05-02 13:40 UTC, rathodmeetsatish commented on docs/resources/platform_connector_tas.md
> +
resource examples are not reflecting in docs

2023-05-02 13:40 UTC, rathodmeetsatish commented on internal/service/platform/connector/tas_data_source.go
> +	helpers.SetMultiLevelDatasourceSchema(resource.Schema)
use SetMultiLevelDatasourceSchemaIdentifierRequired instead of this. Regenrate doc as it will be a schema change

2023-05-02 13:40 UTC, rathodmeetsatish commented on examples/resources/harness_platform_connector_tas/import.sh
> +terraform import harness_platform_connector_tas.example <connector_id>
org and project examples are missing please refer other connectors

2023-05-03 12:39 UTC, RishabhGupta34 commented on docs/data-sources/platform_connector_tas.md
> +
added

2023-05-03 12:39 UTC, RishabhGupta34 commented on docs/resources/platform_connector_tas.md
> +
added

2023-05-03 12:39 UTC, RishabhGupta34 commented on examples/resources/harness_platform_connector_tas/import.sh
> +terraform import harness_platform_connector_tas.example <connector_id>
added

2023-05-03 12:39 UTC, RishabhGupta34 commented on internal/service/platform/connector/tas_test.go
> +
added

2023-05-04 12:43 UTC, rathodmeetsatish approved these changes
Approving it. Merge only if tested on an account in  prod and qa env

2023-05-04 12:46 UTC, rathodmeetsatish requested changes

2023-05-04 12:46 UTC, rathodmeetsatish commented on .changelog/528.txt
> +```release-note:new-resource
file name should be same as pr number

2023-05-05 08:11 UTC, RishabhGupta34 commented on .changelog/528.txt
> +```release-note:new-resource
done

2023-05-05 08:14 UTC, rathodmeetsatish approved these changes

2023-05-05 09:34 UTC, merged