feat: [PL-38509]: Added apiKey resource
harness/terraform-provider-harness pull request #532
Opened 2023-05-08 14:33 UTC by VikasMaddukuriHarness

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-05-09 07:19 UTC, rijajoo requested changes
Please address all these comments in all places. Also please add changelog for newer resource added.

2023-05-09 07:19 UTC, rijajoo commented on internal/provider/provider.go
> +	pl_apiKey "github.com/harness/terraform-provider-harness/internal/service/platform/api_key"
pl_api_key (Casing)

2023-05-09 07:19 UTC, rijajoo commented on internal/service/platform/api_key/apiKey.go
> +				Description: "Name of the ApiKey",
Name of the Api Key

2023-05-09 07:19 UTC, rijajoo commented on internal/service/platform/api_key/data_source_apiKey.go
> +		return diag.FromErr(errors.New("identifier  must be specified"))
Identifier must be specified (spacing, capitalization)

2023-05-15 07:48 UTC, rijajoo requested changes

2023-05-15 10:00 UTC, rathodmeetsatish commented
trigger build

2023-05-15 10:02 UTC, adiyaar24 commented
trigger subcategoryfieldcheck

2023-05-15 10:04 UTC, adiyaar24 approved these changes

2023-05-15 10:05 UTC, merged