CI-8165: fixing github conn
harness/terraform-provider-harness pull request #553
Opened 2023-05-26 21:22 UTC by RajBaviskar

## Describe your changes

- Adding support for execute on delegate 

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-06-02 21:05 UTC, abhinav-harness approved these changes

2023-06-06 06:37 UTC, rathodmeetsatish requested changes

2023-06-06 06:37 UTC, rathodmeetsatish commented on .changelog/567.txt
> +resource/harness_platform_connector_github: adding support for execute_on_delegate.
changelog file name is incorrect

2023-06-06 07:16 UTC, rathodmeetsatish submitted a review, later dismissed

2023-06-07 18:29 UTC, arvind-choudhary-h approved these changes

2023-06-07 18:30 UTC, merged