feat: [CDS-56689]: Add rancher connector
harness/terraform-provider-harness pull request #598
Opened 2023-06-28 16:51 UTC by abhinavsingh1196

## Describe your changes

go-sdk entities change here: https://github.com/harness/harness-go-sdk/pull/347

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-06-29 06:55 UTC, rathodmeetsatish submitted a review, later dismissed

2023-06-29 10:31 UTC, abosii-harness requested changes

2023-06-29 10:31 UTC, abosii-harness commented on internal/service/platform/connector/k8s_rancher.go
> +						"password_ref": {
Should be this bearer_token_ref?

2023-06-29 10:31 UTC, abosii-harness commented on internal/service/platform/connector/k8s_rancher.go
> +						"rancher_url": {
Does it make sense to have rancher_url as part of the bearer_token?

2023-06-29 11:10 UTC, abhinavsingh1196 commented on internal/service/platform/connector/k8s_rancher.go
> +						"password_ref": {
yes, renamed

2023-06-29 11:11 UTC, abhinavsingh1196 commented on internal/service/platform/connector/k8s_rancher.go
> +						"rancher_url": {
It makes more sense to keep it out. moved it, thanks

2023-06-29 12:35 UTC, abosii-harness approved these changes

2023-06-30 07:33 UTC, rathodmeetsatish submitted a review, later dismissed

2023-06-30 07:38 UTC, deepakbolangady submitted a review, later dismissed
I've requested some minor changes. However, I don't want to block this PR, so I'm approving it. If this PR needs another approval from me, please reach out.

2023-06-30 07:38 UTC, deepakbolangady commented on .changelog/598.txt
> +harness_platform_connector_rancher - Added rancher connector in harness terraform provider
(Global suggestion)
```suggestion
harness_platform_connector_rancher - Added a Rancher connector to the Terraform Harness provider.
```
Is it "Harness Terraform provider" or "Terraform Harness provider"? Has Harness created a Terraform provider or has Terraform enabled Harness to create a provider? If we expand to "Harness provider for Terraform", we might get the answer: "Terraform Harness provider" sounds better, so I'm leaning toward the latter. 

For now, we can hold this thought and maybe just use uppercase "H" and "T" globally. Retain the case of "p" in "provider" (should be lowercase). I will do some research and come back on which one is the adjective. 

Rancher is a company/product. Use uppercase. Globally.

2023-06-30 07:38 UTC, deepakbolangady commented on docs/data-sources/platform_connector_rancher.md
> +subcategory: "Next Gen"
NextGen is one word. I know it cannot be done piecemeal. Can it be corrected globally sometime?

2023-06-30 07:38 UTC, deepakbolangady commented on docs/data-sources/platform_connector_rancher.md
> +Datasource for looking up a Rancher connector.
```suggestion
Data source for looking up a Rancher connector.
```

2023-06-30 07:38 UTC, deepakbolangady commented on docs/data-sources/platform_connector_rancher.md
> +## Example Usage
```suggestion
## Example usage
```
(Use sentence case in titles. We do that in docs. If this is a heavy lift, set aside for now.)

2023-06-30 07:38 UTC, deepakbolangady commented on internal/service/platform/connector/k8s_rancher_data_source.go
> +		Description: "Datasource for looking up a Rancher connector.",
```suggestion
		Description: "Data source for looking up a Rancher connector.",
```
(Maybe check globally?)

2023-06-30 08:12 UTC, abhinavsingh1196 commented on internal/service/platform/connector/k8s_rancher_data_source.go
> +		Description: "Datasource for looking up a Rancher connector.",
Done

2023-06-30 08:13 UTC, abhinavsingh1196 commented on docs/data-sources/platform_connector_rancher.md
> +Datasource for looking up a Rancher connector.
Done

2023-06-30 08:29 UTC, abosii-harness approved these changes

2023-06-30 08:29 UTC, rathodmeetsatish approved these changes

2023-06-30 08:37 UTC, merged