[feat]: [CDS-69600]: Fix yaml null issue for environment data source Api
harness/terraform-provider-harness pull request #610
Opened 2023-07-05 10:32 UTC by lovish1999

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-07-06 06:10 UTC, rathodmeetsatish requested changes

2023-07-06 06:10 UTC, rathodmeetsatish commented on .changelog/601.txt
> + Fix for supporting yaml for environment and environment group data source
file name shoulf be 610 right?

2023-07-06 06:38 UTC, lovish1999 commented on .changelog/601.txt
> + Fix for supporting yaml for environment and environment group data source
Changed. But why ?

2023-07-07 07:55 UTC, tchaurasiya approved these changes

2023-07-07 08:35 UTC, lovish1999 commented on internal/service/platform/environment/data_source_environment.go
> +				Description: "Environment YAML." + helpers.Descriptions.YamlText.String(),
It adds this description - "In YAML, to reference an entity at the organization scope, prefix 'org' to the expression: org.{identifier}. To reference an entity at the account scope, prefix 'account` to the expression: account.{identifier}. For eg, to reference a connector with identifier 'connectorId' at the organization scope in a stage mention it as connectorRef: org.connectorId."

2023-07-07 08:51 UTC, rathodmeetsatish approved these changes

2023-07-07 09:47 UTC, merged