feat:[CDS-69871]: supported refresh token auth in snow connector
harness/terraform-provider-harness pull request #614
Opened 2023-07-11 11:51 UTC by naman-goenka

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-07-14 13:41 UTC, abhinavmittal-harness approved these changes

2023-07-14 14:15 UTC, rathodmeetsatish requested changes
please get the ff enabled

2023-07-17 06:28 UTC, naman-goenka commented
> please get the ff enabled

FF has been enabled @rathodmeetsatish

2023-07-17 10:25 UTC, rathodmeetsatish approved these changes

2023-07-17 11:21 UTC, merged