[CDS-45765]: Terraform plugin for FileStore
harness/terraform-provider-harness pull request #629
Opened 2023-07-21 14:19 UTC by ivan-83

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-07-26 08:57 UTC, rathodmeetsatish requested changes

2023-07-26 08:57 UTC, rathodmeetsatish commented on internal/service/platform/file_store/data_source_file.go
> +				Optional:    false,
is content required? if yes then i guess we should explicitly set required: true same at other places

2023-07-26 08:57 UTC, rathodmeetsatish commented on internal/service/platform/file_store/data_source_folder.go
> +	helpers.SetMultiLevelResourceSchema(resource.Schema)
if identifier is required for get call use setmultileveldataschemawithidentifier required

2023-07-26 08:57 UTC, rathodmeetsatish commented on internal/service/platform/file_store/data_source_file.go
> +	helpers.SetMultiLevelResourceSchema(resource.Schema)
if identifier is required for get call use setmultileveldataschemawithidentifier required

2023-07-26 08:57 UTC, rathodmeetsatish commented on internal/service/platform/file_store/resource_file_test.go
> +
please add a deleteUnderlyingResource test refer other test files to check how to add it same for folder

2023-07-26 13:58 UTC, ivan-83 commented on internal/service/platform/file_store/data_source_file.go
> +				Optional:    false,
The content is not required. 
We are having two options to ask users to provide the content of the file and the content should be put in terraform file resources, which could be difficult to read/update/maintain the terraform file.

Based on it I decided to add the file_content_path property which is the path to the file from where to upload content on Harness File Store. The content is read-only retrieved from Harness File Store and will contain uploaded file content and it should be used while getting file store file resources.

Properties while creating the file store file resource,
`resource "harness_platform_file_store_file" "example" {
  org_id            = "org_id"
  project_id        = "project_id"
  identifier        = "identifier"
  name              = "name"
  description       = "description"
  tags              = ["foo:bar", "baz:qux"]
  parent_identifier = "parent_identifier"
  file_content_path = "file_content_path"
  mime_type         = "mime_type"
  file_usage        = "MANIFEST_FILE|CONFIG|SCRIPT"
}`

2023-07-26 14:49 UTC, ivan-83 commented on internal/service/platform/file_store/data_source_file.go
> +	helpers.SetMultiLevelResourceSchema(resource.Schema)
Done.

2023-07-26 15:52 UTC, rathodmeetsatish requested changes

2023-07-26 15:52 UTC, rathodmeetsatish commented on internal/service/platform/file_store/data_source_file.go
> +	helpers.SetMultiLevelDatasourceSchemaIdentifierRequired(resource.Schema)
this will require you to regenerate docs

2023-07-26 15:52 UTC, rathodmeetsatish commented on internal/service/platform/file_store/data_source_folder.go
> +	helpers.SetMultiLevelDatasourceSchemaIdentifierRequired(resource.Schema)
this will require you to regenerate docs

2023-07-26 19:42 UTC, ivan-83 commented on internal/service/platform/file_store/data_source_folder.go
> +	helpers.SetMultiLevelDatasourceSchemaIdentifierRequired(resource.Schema)
Done.

2023-07-26 19:42 UTC, ivan-83 commented on internal/service/platform/file_store/data_source_file.go
> +	helpers.SetMultiLevelDatasourceSchemaIdentifierRequired(resource.Schema)
Done.

2023-07-27 10:07 UTC, rathodmeetsatish approved these changes

2023-07-27 10:21 UTC, merged