feat: [CDS-73704]: add support for OCI helm with ESO
harness/terraform-provider-harness pull request #638
Opened 2023-07-31 16:16 UTC by mteodor

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-07-31 18:32 UTC, manavjot-harness approved these changes

2023-07-31 18:36 UTC, manavjot-harness requested changes
update the go mod with the go sdk with your changes once they are released.

2023-08-01 09:49 UTC, rathodmeetsatish submitted a review, later dismissed

2023-08-01 10:21 UTC, mteodor commented
trigger build

2023-08-01 13:32 UTC, manavjot-harness approved these changes

2023-08-01 13:36 UTC, rathodmeetsatish approved these changes

2023-08-01 14:14 UTC, merged