[fix]: [SRM-15255]: Removing enabled scope from terraform
harness/terraform-provider-harness pull request #640
Opened 2023-08-03 09:27 UTC by deepak-harness

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-08-03 11:55 UTC, iamtcreddy approved these changes

2023-08-03 11:58 UTC, rathodmeetsatish requested changes
schema has changed please update docs and add chnagelog file

2023-08-10 20:37 UTC, RajBaviskar commented
@deepak-harness Even though it was an optional field. Work with PM to communicate this with the customer.

2023-08-10 20:38 UTC, RajBaviskar commented
@deepak-harness Please ask someone from SRM team to review this as well.

2023-08-11 08:26 UTC, merged