FFM-9085: Add a terraform resource to create a new target
harness/terraform-provider-harness pull request #660
Opened 2023-08-22 18:53 UTC by ribeirophillipe

## Describe your changes
* Implement CRUD actions for creating a new target in terraform
* Add all the interfaces and implementations
* 
## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-08-22 19:18 UTC, rohitk-h reviewed
Please add unit tests for the resource. Ref https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21122646032/Terraform+Onboarding+and+Quickstart+for+Creating+Resource+in+Provider

2023-08-28 14:34 UTC, ribeirophillipe commented
@rohitk-h unit tests were added!

2023-08-28 14:53 UTC, rathodmeetsatish requested changes
Remove makefile changes, tf_build.sh

2023-08-29 10:21 UTC, ribeirophillipe commented
@rathodmeetsatish done

2023-08-29 15:14 UTC, davejohnston submitted a review, later dismissed
This looks good. Ship it

2023-08-29 15:42 UTC, rathodmeetsatish requested changes
generate docs and add changelog file

2023-08-29 15:42 UTC, rathodmeetsatish commented on internal/service/platform/user/resource_user.go
> +					},
remove these changes

2023-08-29 15:42 UTC, rathodmeetsatish commented on internal/service/cd/delegate/delegate_helper_test.go
> -	err = cli.ContainerStop(context.Background(), name, nil)
why have we changed this revert if not needed

2023-08-30 09:43 UTC, ribeirophillipe commented on internal/service/platform/user/resource_user.go
> +					},
done

2023-08-30 09:43 UTC, ribeirophillipe commented on internal/service/cd/delegate/delegate_helper_test.go
> -	err = cli.ContainerStop(context.Background(), name, nil)
it gives a compilation error ...

2023-08-30 12:16 UTC, rathodmeetsatish requested changes

2023-08-30 12:16 UTC, rathodmeetsatish commented on .changelog/670.txt
> +```release-note:new-resource
add a file corresponding to your pr number which is 660

2023-08-30 12:16 UTC, rathodmeetsatish commented on examples/data-sources/harness_platform_monitored_service/data-source.tf
> -  org_id = "org_id"
remove changes which dont belong to ff

2023-08-30 12:16 UTC, rathodmeetsatish commented on examples/data-sources/harness_platform_slo/data-source.tf
> -  org_id = "org_id"
remove changes which dont belong to ff

2023-08-30 12:16 UTC, rathodmeetsatish commented on examples/resources/harness_platform_policyset/resource.tf
> +  org_id     = "terraform_example_org"
remove changes which dont belong to ff

2023-08-30 12:16 UTC, rathodmeetsatish commented on examples/resources/harness_platform_slo/resource.tf
>    identifier = "identifier"
remove changes which dont belong to ff

2023-08-30 12:16 UTC, rathodmeetsatish commented on internal/service/cd/delegate/delegate_helper_test.go
> -	err = cli.ContainerStop(context.Background(), name, nil)
remove changes which dont belong to ff

2023-08-30 13:56 UTC, rathodmeetsatish requested changes

2023-08-30 13:56 UTC, rathodmeetsatish commented on docs/resources/platform_feature_flag_target.md
> +subcategory: ""
subcategory: "NextGen"

2023-08-30 14:12 UTC, rathodmeetsatish approved these changes

2023-08-30 14:13 UTC, merged