FFM-9086: Add a terraform resource to create a new target group
harness/terraform-provider-harness pull request #661
Opened 2023-08-23 10:10 UTC by ribeirophillipe

## Describe your changes
* Add resource feature_flag_target_group
* Add unit tests
* 
## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-08-31 11:40 UTC, davejohnston commented on Makefile
> +	go test $(SWEEP_DIR) -v -sweep=all $(SWEEPARGS) -timeout 60m
Think this is just whitespace.

2023-08-31 11:40 UTC, davejohnston commented on examples/resources/harness_platform_slo/resource.tf
> +}
more whitespace

2023-08-31 11:41 UTC, davejohnston commented on internal/provider/provider.go
> +	featureflagtargetgroup "github.com/harness/terraform-provider-harness/internal/service/platform/feature_flag_target_group"
do we need to alias this?

2023-08-31 11:41 UTC, davejohnston commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +			"included": {
I would phrase this as "A list of targets to to include in the target group"

2023-08-31 11:42 UTC, davejohnston commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +				Description: "The list of rules to include in the feature flag target group.",
typo here - it says include but should be exclude.  Similar to above, I'd state its a list of 'targets' to be excluded from the target group

2023-08-31 11:42 UTC, davejohnston commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +				Description: "The list of rules to exclude in the feature flag target group.",
This should be 'include' not exclude

2023-08-31 11:43 UTC, davejohnston commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +						"id": {
I don't think we should expose this 'id'.  It should be generated automatically on the server-side.

2023-08-31 11:43 UTC, davejohnston commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +	time.Sleep(1 * time.Second)
Do we need this sleep?  If we check the status code from httpResp that might be more reliable.

2023-08-31 11:45 UTC, davejohnston reviewed
Overall looks good.
There is some whitespace changes to files that can be reverted.
Take a look at the descriptions fro the resources, I think these  need some changes.
One query over the sleep - do we need to use it, could we check the resp code from the create operation?

2023-09-01 11:53 UTC, ribeirophillipe commented on internal/provider/provider.go
> +	featureflagtargetgroup "github.com/harness/terraform-provider-harness/internal/service/platform/feature_flag_target_group"
compiler complained without one ...

2023-09-01 11:54 UTC, ribeirophillipe commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +						"id": {
that was based on the original schema... I will remove it.

2023-09-01 11:55 UTC, ribeirophillipe commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +	time.Sleep(1 * time.Second)
done

2023-09-01 12:03 UTC, davejohnston commented on internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
> +				Description: "The list of rules to include in the feature flag target group.",
```suggestion
				Description: "The list of rules used to include targets in the target group.",
```

2023-09-01 12:04 UTC, davejohnston submitted a review, later dismissed
Please make one last change to the rules description.
```The list of rules used to include targets in the target group```

2023-09-01 12:07 UTC, rathodmeetsatish requested changes

2023-09-01 12:07 UTC, rathodmeetsatish commented on internal/service/cd/delegate/delegate_helper_test.go
> +	err = cli.ContainerStop(context.Background(), name, container.StopOptions{})
remove changes not related to ff

2023-09-01 12:08 UTC, rathodmeetsatish requested changes
generate docs

2023-09-01 12:14 UTC, rathodmeetsatish commented
trigger build

2023-09-01 12:21 UTC, rathodmeetsatish approved these changes

2023-09-01 12:24 UTC, merged

2023-09-01 12:24 UTC, davejohnston approved these changes
Looks good