Update stable version of the template
harness/terraform-provider-harness pull request #675
Opened 2023-09-06 14:22 UTC by vtxorxwitty

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

2023-09-06 17:30 UTC, RajBaviskar approved these changes

2023-09-06 17:31 UTC, RajBaviskar commented
@vtxorxwitty in testing please make sure all the existing behavior is tested.

2023-09-07 07:08 UTC, rathodmeetsatish requested changes
add changelog file

2023-09-07 07:46 UTC, rathodmeetsatish approved these changes

2023-09-08 14:27 UTC, merged