CI-9639: added github_app support in http  credentials
harness/terraform-provider-harness pull request #703
Opened 2023-09-26 12:36 UTC by sahithibanda01

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

2023-09-26 15:12 UTC, rathodmeetsatish requested changes
add test in github_test.go and test it pointing to qa and prod

2023-09-26 15:13 UTC, rathodmeetsatish requested changes

2023-09-26 15:13 UTC, rathodmeetsatish commented on examples/resources/harness_platform_connector_github/resource.tf
> +resource "harness_platform_connector_github" "test" {
changes in example folder will require doc update

2023-09-27 05:46 UTC, smjt-h commented on go.mod
> +	github.com/harness/harness-go-sdk v0.3.52-0.20230926100809-9d31d2a3e28f
Lets test after importing latest sdk

2023-09-29 11:18 UTC, smjt-h commented
Validate support for datasource as well `harness_platform_connector_github`

2023-09-29 12:07 UTC, smjt-h approved these changes

2023-09-29 13:24 UTC, rathodmeetsatish requested changes
Add changelog file corresponding to your pr number

2023-10-03 06:11 UTC, rathodmeetsatish requested changes

2023-10-03 06:11 UTC, rathodmeetsatish commented on .changelog/703.txt
> +```release-note:added new feature in a resource
this is enhancement please refer to some file where we have done enchancement and use the same template

2023-10-03 06:42 UTC, rathodmeetsatish approved these changes

2023-10-03 06:55 UTC, autociuser commented on examples/resources/harness_platform_connector_github/resource.tf
> +resource "harness_platform_connector_github" "test" {
done

2023-10-03 06:58 UTC, sahithibanda01 commented on examples/resources/harness_platform_connector_github/resource.tf
> +resource "harness_platform_connector_github" "test" {
done

2023-10-03 07:01 UTC, merged