IAC-1124: add iacm workspaces
harness/terraform-provider-harness pull request #726
Opened 2023-10-26 13:31 UTC by dwarren-dev

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

2023-10-26 13:44 UTC, dwarren-dev commented
trigger subcategoryfieldcheck

2023-10-26 13:59 UTC, rathodmeetsatish commented on .changelog/720.txt
> +```
changelog file name should be corresponding to the pr umber i this case it is 726

2023-10-26 13:59 UTC, rathodmeetsatish requested changes
added comment

2023-10-31 10:10 UTC, allofthesepeople approved these changes

2023-10-31 10:32 UTC, nassergonzalez submitted a review, later dismissed

2023-11-02 10:51 UTC, dwarren-dev commented on docs/data-sources/platform_workspace.md
> +subcategory: ""
@rathodmeetsatish i made these changes, can you re-review?

2023-11-02 10:53 UTC, rathodmeetsatish requested changes

2023-11-02 10:53 UTC, rathodmeetsatish commented on .changelog/726.txt
> +```release-note:new-data-source
we only have 3 options here new-resource, enhancement, fix

2023-11-06 15:51 UTC, dwarren-dev commented on .changelog/726.txt
> +```release-note:new-data-source
@rathodmeetsatish thanks, fixed this in my latest commit

2023-11-06 16:59 UTC, rathodmeetsatish submitted a review, later dismissed

2023-11-08 10:51 UTC, nassergonzalez approved these changes

2023-11-08 11:31 UTC, merged