fix: [CDS-82953]: Add force delete option for aws, azure, gcp, k8s, rancher, oci and helm connectors
harness/terraform-provider-harness pull request #743
Opened 2023-11-08 09:00 UTC by abosii-harness

## Describe your changes
This changes provide the force_delete option for next connectors:
- [x] GCP
- [x] AWS
- [x] Azure
- [x] Kubernetes
- [x] Rancher
- [x] Oci Helm
- [x] Http Helm

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

2023-11-08 09:15 UTC, abosii-harness commented
Doc ticket: https://harness.atlassian.net/browse/DOC-3888

2023-11-08 09:58 UTC, acasian-harness commented on internal/service/platform/connector/azure_cloud_provider.go
> +				Type:        schema.TypeString,
shouldn't it by boolean?

2023-11-08 09:58 UTC, acasian-harness approved these changes

2023-11-08 10:19 UTC, abosii-harness commented on internal/service/platform/connector/azure_cloud_provider.go
> +				Type:        schema.TypeString,
copy paste, not sure why in other places this is string, checking

2023-11-08 10:45 UTC, abosii-harness commented on internal/service/platform/connector/azure_cloud_provider.go
> +				Type:        schema.TypeString,
there was no reason to put it as string before, update to bool

2023-11-08 17:14 UTC, abhinavsingh1196 approved these changes

2023-11-09 04:52 UTC, GoelPratyush99 approved these changes

2023-11-09 05:35 UTC, TarunUba1 approved these changes

2023-11-10 13:54 UTC, rathodmeetsatish requested changes
include connector tests in terraform cd pipeline

2023-11-10 14:05 UTC, rathodmeetsatish approved these changes

2023-11-10 15:04 UTC, merged