Add repo provider
harness/terraform-provider-harness pull request #879
Opened 2024-01-26 13:58 UTC by darkodraskovic

## Describe your changes

This will a terraform provider for a Repository resource defined in gitness `types/repo.go`.

2024-02-13 05:09 UTC, abhinav-harness commented on internal/session.go
> +	cfg.BasePath = utils.GetEnv("HARNESS_ENDPOINT", "") + "/code/api/v1"
make /code/api/v1 as constant

2024-02-13 08:59 UTC, rathodmeetsatish commented on internal/service/platform/repo/resource_repo.go
> +type RepoBody struct {
it better if this is in harness-go-sdk similarly other body in this pr

2024-02-13 11:33 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +type RepoBody struct {
Unfortunatelly, we have only `interface{}` in the  harness-go-sdk.

2024-02-14 02:49 UTC, abhinav-harness commented on examples/data-sources/harness_platform_repo/data-source.tf
> +  project_identifier = "prj_id"
prj -> proj

2024-02-14 02:50 UTC, johannesHarness commented on docs/resources/platform_repo.md
> +  type               = "github"
as mentioned, all provider related things should be either under a `provider` or `source` field of `RepoProvider` type or sth like that, so that we have sth like
```go
resource "harness_platform_repo" "test" {
  identifier         = "test_repo_123"
  name               = "test_repo_123"
  org_identifier     = "test_org_123"
  project_identifier = "test_project_123"
  default_branch     = "main"
  description        = "test_description_123"
  account_id         = "account_id"
  is_public          = true
  source = {
      type = "github"
      username...
      password....
      host ....
      repo ...
  }
```

2024-02-14 02:51 UTC, abhinav-harness commented on internal/service/platform/repo/resource_repo.go
> +type RepoBody struct {
lets create a followup - it is better to move this to go-sdk

2024-02-14 02:53 UTC, johannesHarness commented on docs/resources/platform_repo.md
> +- `parent_ref` (String) Reference to the parent repository.
are we actually supporting org_id and org_identifier? and why do they have different descriptions?

2024-02-14 02:54 UTC, johannesHarness commented on docs/resources/platform_repo.md
> +- `pipelines` (String) The provider repo pipelines when importing.
this is disabled for now in harness AFAIK. we should remove it from here for now?

2024-02-14 02:55 UTC, abhinav-harness commented on internal/service/platform/repo/resource_repo.go
> +	meta interface{},
@darkodraskovic i think tf has a way to see field A or B - can we try for import or create similar thing?

2024-02-14 02:56 UTC, johannesHarness commented on examples/resources/harness_platform_repo/import.sh
> +terraform import harness_platform_repo.example <repo_identifier>
might be me not knowing terraform too well, but where's the accountid coming from?

2024-02-14 02:57 UTC, johannesHarness commented on internal/provider/provider.go
> +				"harness_platform_repo":                            repo.ResourceRepo(),
why is it under `platform` - seems off to me? just `harness_repo` or maybe `harness_code_repo`?

2024-02-14 03:00 UTC, johannesHarness commented on internal/service/platform/repo/data_source_repo.go
> +	orgId := d.Get("org_identifier").(string)
I checked 3 other random harness resources, and they all used `d.Get("org_id")` and `d.Get("project_id")` - we should be consistent.

2024-02-14 03:01 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	Identifier    string `json:"identifier"`
@abhinav-harness shouldn't we have these structs from the SDK?

2024-02-14 03:03 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	orgId := d.Get("org_identifier").(string)
same here

2024-02-14 03:04 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	orgId := d.Get("org_identifier").(string)
same here

2024-02-14 03:04 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	providerRepo := d.Get("provider_repo").(string)
see comment on better structure for import data (like source subobject)

2024-02-14 03:05 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +				OrgIdentifier:     optional.NewString(d.Get("org_identifier").(string)),
you already have the orgId and projId here.

2024-02-14 03:06 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	orgId := d.Get("org_identifier").(string)
org**ID** since we have account**ID** (same for projectID)

2024-02-14 03:06 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	if err != nil {
we already check err in both if and else case. either remove it in the cases, or remove this one here

2024-02-14 03:06 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	orgId := d.Get("org_identifier").(string)
same here

2024-02-14 03:07 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +func generateId(identifier, accId, orgId, prjId string) string {
why is that our ID? could we make it `account/org/proj/repo` instead? (or account/org/repo or account/repo depending on where it is located?)

2024-02-14 03:08 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		ForkID:        int64(d.Get("fork_id").(int)),
we don't have that yet - can keep it off for now?

2024-02-14 03:09 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		ParentRef:     d.Get("parent_ref").(string),
remove parentref from body - not used for harness-api format.

2024-02-14 03:10 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		ParentRef:   d.Get("parent_ref").(string),
same here, remove

2024-02-14 03:10 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Host:     d.Get("provider_config.host").(string),
maybe `source` might be more understandable?

2024-02-14 03:11 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	d.Set("num_forks", repo.NumForks)
remove fork info I'd say

2024-02-14 03:12 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"org_identifier": {
org_id + project_id

2024-02-14 03:12 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description: "Name of the config.",
name of the repo?

2024-02-14 03:12 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"fork_id": {
remove

2024-02-14 03:12 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"num_forks": {
remove

2024-02-14 03:13 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"parent_ref": {
remove

2024-02-14 03:13 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"provider_repo": {
move to provider_config / source

2024-02-14 03:13 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"provider_config": {
maybe name it `source` or sth like that?

2024-02-14 03:13 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +						Description: "The type of import (e.g., github).",
can we make this an enum? (or at least provide all available values?)

2024-02-14 11:38 UTC, darkodraskovic commented on docs/resources/platform_repo.md
> +- `parent_ref` (String) Reference to the parent repository.
This is error on the part of the doc generation. I will check into it.

2024-02-14 11:41 UTC, darkodraskovic commented on docs/resources/platform_repo.md
> +- `pipelines` (String) The provider repo pipelines when importing.
Can you be more specific? Do you think about `parent_ref`?

2024-02-14 11:43 UTC, darkodraskovic commented on examples/resources/harness_platform_repo/import.sh
> +terraform import harness_platform_repo.example <repo_identifier>
It's our account id.

2024-02-14 11:43 UTC, darkodraskovic commented on internal/service/platform/repo/data_source_repo.go
> +	orgId := d.Get("org_identifier").(string)
I was following naming convention in json. I can rename.

2024-02-14 11:49 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +	Identifier    string `json:"identifier"`
Unfortunatelly, this does not seem to be in the SDK.

2024-02-14 11:51 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +	orgId := d.Get("org_identifier").(string)
I've chosen to follow tf convention and use `accountId`.

2024-02-14 11:55 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +		ForkID:        int64(d.Get("fork_id").(int)),
`ForkID`?

2024-02-14 11:59 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +			Description: "Name of the config.",
This is for some reason required by tf. It's the name of the resource I think. Don't know why it's needed.

2024-02-14 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/terraform-provider-harness?pullRequest=879) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/terraform-provider-harness?pullRequest=879) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/terraform-provider-harness?pullRequest=879) it.</sub>

2024-02-14 13:55 UTC, darkodraskovic commented on internal/provider/provider.go
> +				"harness_platform_repo":                            repo.ResourceRepo(),
Because org and project are under harness_platform_.

2024-02-15 01:46 UTC, johannesHarness commented on docs/resources/platform_repo.md
> +- `pipelines` (String) The provider repo pipelines when importing.
pipelines

2024-02-15 01:47 UTC, johannesHarness commented on examples/resources/harness_platform_repo/import.sh
> +terraform import harness_platform_repo.example <repo_identifier>
as in where does the user provide it

2024-02-15 01:47 UTC, johannesHarness commented on internal/provider/provider.go
> +				"harness_platform_repo":                            repo.ResourceRepo(),
but org and project belong to harness_platform. we are not a platform feature / resource per se.

2024-02-15 01:48 UTC, johannesHarness commented on internal/service/platform/repo/data_source_repo.go
> +	orgId := d.Get("org_identifier").(string)
yes rename for consistency in terrafoirm

2024-02-15 01:49 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	Identifier    string `json:"identifier"`
@abhinav-harness can you take a look

2024-02-15 01:50 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		ForkID:        int64(d.Get("fork_id").(int)),
correct, forkid - does github not show the line that I commented on?

2024-02-15 01:51 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description: "Name of the config.",
no as in the value of `Description` should be `Name of the repo` not `name of the config`

2024-02-15 01:52 UTC, johannesHarness commented on internal/provider/provider.go
> +				"harness_platform_repo":                            repo.ResourceRepo(),
cc @hitesharinga @abhinav-harness

2024-02-15 01:55 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	if source != nil {
if source is nil this should be an error, no?

2024-02-15 01:55 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		importBody.Pipelines = source["pipelines"].(string)
I think we should remove that until supported (pipelines flag on import)

2024-02-15 01:56 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description: "Name of the resource.",
**minor** `name of the repository` to match everything else?

2024-02-15 01:57 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description: "ID of the parent repository.",
I feel like we can hide that in terraform? that's the id of the parent space. nothing you can do with it anyway.
@hitesharinga @abhinav-harness what do you think?

2024-02-15 01:58 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +					"pipelines": {
remove pipelines until supported

2024-02-15 01:59 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +						Description: "The type of import (e.g., github).",
also I'd phrase it sth like `The type of SCM provider to import the repo from`

2024-02-15 02:01 UTC, johannesHarness commented on internal/session.go
> +func (s *Session) GetCodeClientWithContext(ctx context.Context) (*code.APIClient, context.Context) {
what's the purpose of the context here? also, how come ours is so different from other harness clients, shouldn't we have roughly the same auth setup and such?

2024-02-15 10:39 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +	if source != nil {
No, because user don't need to supply import source data in resource, e.g. when creating a resource and not importing it.

2024-02-15 10:40 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +			Description: "Name of the resource.",
Seem that `name` is required for every tf resource.

2024-02-15 10:59 UTC, darkodraskovic commented on internal/service/platform/repo/resource_repo.go
> +						Description: "The type of import (e.g., github).",
There is no point of adding an enum here, since we don't do any kind of user error checking or similar. It's just a string and it's user's responsibility to provide a correct string. 

Besides, we don't want to introduce any kind of logic in tf provider of this sort.

2024-02-15 11:16 UTC, darkodraskovic commented on internal/session.go
> +func (s *Session) GetCodeClientWithContext(ctx context.Context) (*code.APIClient, context.Context) {
The context is used when making terraform requests.

2024-02-15 11:17 UTC, darkodraskovic commented on internal/session.go
> +func (s *Session) GetCodeClientWithContext(ctx context.Context) (*code.APIClient, context.Context) {
As to the other question, this was the only way that i've found to set up the url and auth.

2024-02-23 00:57 UTC, johannesHarness commented on examples/resources/harness_platform_repo/resource.tf
> +  account_id     = "account_id"
remove

2024-02-23 00:58 UTC, johannesHarness commented on internal/provider/provider.go
> +		BasePath:      d.Get("endpoint").(string) + "/code/api/v1",
Add todo comment so we remember to remove?

2024-02-23 01:00 UTC, johannesHarness commented on internal/service/platform/repo/data_source_repo.go
> +	repoIdentifier := d.Get("identifier").(string)
do we care about d.Id() at all here?

2024-02-23 01:01 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +	id := d.Id()
this or other read is wrong.

2024-02-23 01:02 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		d.Get("identifier").(string),
check this, too

2024-02-23 01:03 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		id, &code.RepositoryApiDeleteRepositoryOpts{
formatting

2024-02-23 01:03 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			ctx, c.AccountId,
formatting

2024-02-23 01:04 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +func source(d *schema.ResourceData) map[string]interface{} {
`getSource`

2024-02-23 01:05 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Required:    true,
mark as computed

2024-02-23 01:06 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Optional:    true, // handle default branch update
computed + optional block branch update maybe for now?

2024-02-23 01:07 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"id": {
remove maybe?

2024-02-23 01:08 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"size": {
remove all of these application layer user values?

2024-02-23 01:08 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Optional:    true,
optional true + computed true? we'll have to test

2024-02-23 01:09 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"identifier": {
move up

2024-02-23 01:09 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description: "Whether the repository has a readme.",
should be created with a readme

2024-02-23 01:10 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +						Description: "The provider repository to import from.",
requiredwith

2024-02-23 01:10 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo_test.go
> +func testAccResourceRepoImport(identifier, description, providerRepo string) string {
renamne to project or do on account level

2024-02-24 00:56 UTC, johannesHarness commented on go.mod
> +	github.com/harness/harness-go-sdk v0.3.75-0.20240223091726-391b117cdb49
make sure to pull latest release with your other PR merged before merging this

2024-02-24 00:58 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description: "Name of the resource.",
> name of the repository

2024-02-24 00:59 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description:      "Default branch of the repository.",
**minor** we should add in the description for all the `createOnlyFieldDiffFunc` marked fields: `any changes after repository creation are ignored` (or sth like that)

2024-02-24 01:00 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description: "ID of the repository.",
`Internal ID of the repository.`

2024-02-24 01:01 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		"importing": {
I just realized - this field also doesn't really make much sense to return.
Quite the opposite - we should probably pull the repo and only return the import operation once the import succeeded?

Otherwise TF doesn't wait for the full repo creation

2024-02-24 01:03 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +			Description:      "Provider related configurations.",
we can maybe be more specific here: `Configuration for importing an existing hosted repository` or sth along those lines

2024-02-24 01:05 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +						Description: "The provider repository to import from.",
`The full identifier of the repository on the SCM provider's platform.` - or sth along those lines

2024-02-24 01:07 UTC, johannesHarness commented on internal/service/platform/roles/resource_roles_test.go
> +		permissions = ["repo_push", "repo_view"]
shouldn't it be `code_repo_push` and `code_repo_view`? or are we appending `code_` somewhere else?
We should also ensure all permission types?

2024-02-24 01:30 UTC, abhinav-harness commented on internal/service/platform/repo/resource_repo.go
> +		"importing": {
didn't get 
Quite the opposite - `we should probably pull the repo and only return the import operation once the import succeeded?`

2024-02-26 19:25 UTC, johannesHarness submitted a review, later dismissed

2024-02-28 02:06 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		time.Sleep(5 * time.Second)
use select with `time.After` so that you can cancel on context cancel.
We also should have an overal timeout

2024-02-28 02:09 UTC, johannesHarness commented on internal/session.go
> +const codePath = "/code/api/v1"
is this being used?

2024-02-28 02:16 UTC, abhinav-harness commented on internal/service/platform/repo/resource_repo.go
> +		time.Sleep(5 * time.Second)
I read doc - they have overall timeout defaulted to 20 mins and i did test that

2024-02-28 02:24 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		time.Sleep(5 * time.Second)
sounds good.

2024-02-28 02:25 UTC, johannesHarness commented on internal/service/platform/repo/resource_repo.go
> +		time.Sleep(5 * time.Second)
but for time.After - that should be in a select-case, together with `<-ctx.Done()`

2024-02-28 02:31 UTC, abhinav-harness commented on internal/service/platform/repo/resource_repo.go
> +		time.Sleep(5 * time.Second)
done

2024-02-28 06:14 UTC, rathodmeetsatish requested changes

2024-02-28 06:14 UTC, rathodmeetsatish commented on go.mod
> +	github.com/harness/harness-go-sdk v0.3.75-0.20240224012509-bb167a107452
use go sdk pipeline to relase new version

2024-02-28 06:14 UTC, rathodmeetsatish commented on go.mod
> +go 1.19
Dont change the go version in this pr

2024-02-28 23:24 UTC, johannesHarness approved these changes

2024-03-05 07:07 UTC, closed without merging