feat: add gcp oidc connector
harness/terraform-provider-harness pull request #968
Opened 2024-04-05 19:59 UTC by eahrend

## Describe your changes
This PR adds the ability to create GCP OIDC connectors in terraform.

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

2024-04-25 07:23 UTC, Raghav-Murali commented on internal/service/platform/connector/gcp.go
> +		connector.Gcp.Credential.Type_ = "OidcAuthentication"
I think it would be better to define a constant for "OidcAuthentication" in `nextgen.GcpAuthTypes.`

2024-04-25 07:24 UTC, Raghav-Murali requested changes
nit: couple of minor comments.

2024-04-25 15:06 UTC, eahrend commented on internal/service/platform/connector/gcp.go
> +	case "OidcAuthentication":
Pending merge of https://github.com/harness/harness-go-sdk/pull/519

2024-08-18 01:10 UTC, closed without merging

2024-08-18 01:10 UTC, bot2-harness commented
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!